### ISSUE TITLE
Versioning module for construction elements

### ISSUE THREAD

**Issue by hlg** [opengeospatial/CityGML-3.0CM#1]
The construction, renovation and demolition dates for construction elements imply changes that might as well be tracked by using the new versioning module. Why are they modeled as explicit attributes?

**Comment by TatjanaKutzner** [comment]
The discussion in the Modelling Subgroup showed that we have to explain the semantics of the different attributes more clearer. All attributes are required in the model as they are used for different purposes:
- "creationDate" and "terminationDate" represent database timestamps, i.e. the time period a specific version of an object is an integral part of the 3D city model
- "validFrom" and "validTo" refer to the lifespan a specific version of an object exists in the real world
- "dateOfConstruction" and "dateOfDemolition" refer to the lifespan the whole object exists in the real world
