### ISSUE TITLE
Codelists - CodeType, ReferenceType or Something New and Better

### ISSUE THREAD

**Issue by 3DXScape** [opengeospatial/CityGML-3.0CM#10]
We need to decide on this. I hope we can follow the 1. Enumeration (fully normative), 2. Extensible (normative base but extensible), 3. Pluggable (completely appplication-dependent)

**Comment by 3DXScape** [comment]
![image](https://user-images.githubusercontent.com/4260590/56330652-dc64be80-613d-11e9-8c2c-7ddf7fe7788e.png)

**Comment by 3DXScape** [comment]
I have revisited the codelist archaeology that was part of the LandInfra SWG work and also reviewed a wider range of the use of codelists in modern standards. The use cases and approaches follow a number of different threads, many of which are XML-specific, use a different encoding for the lists than the base model, or use complex types for the codelist values. In my previous comment, I make a proposal that I think covers the CityGML use cases.

**Comment by 3DXScape** [comment]
A slight correction:

![image](https://user-images.githubusercontent.com/4260590/56336761-5012c580-6156-11e9-804f-84c353ea30ed.png)

**Comment by 3DXScape** [comment]
Some further changes and clarifications based on feedback:
![image](https://user-images.githubusercontent.com/4260590/56338878-c61c2a00-6160-11e9-97ef-3f111c7f52e0.png)

**Comment by 3DXScape** [comment]
Some simplifications and an example based on the discussion in the last meeting.
![image](https://user-images.githubusercontent.com/4260590/57058309-00f38700-6c64-11e9-9103-7b24dc9267d6.png)

**Comment by 3DXScape** [comment]
With some explanation:

![image](https://user-images.githubusercontent.com/4260590/57110466-8111ff00-6ced-11e9-9fd8-0103ea06cc31.png)

**Comment by 3DXScape** [comment]
I started a new document to capture this discussion and my research. The document should eventually be a contribution to part of the specification on codelists so I put it in the Conceptual Model folder at https://github.com/opengeospatial/CityGML-3.0CM/blob/master/Conceptual%20Model/CodeListCityGML3.0-2019.05.10.pdf

**Comment by TatjanaKutzner** [comment]
We discussed at the last web conference that we would like to represent coded values in instance documents in the same way as it was done in CityGML 2.0, e.g.:
~~~ xml
<Furniture>
    <type>stationary</type>
</Furniture>
~~~

However, as we intend to switch to GML 3.3, this won't be possible any more. The GML 3.3 specification says: "a UML attribute whose type is a class stereotyped `<<CodeList>>` is mapped to an element with
either a reference to the corresponding dictionary entry (type gml:ReferenceType) or a string value (value domain: values of the code list).

This means that the UML attribute "type" is either encoded in the form
~~~ xml
<element maxOccurs="unbounded" minOccurs="1" name="type" type="gml:ReferenceType">
    <annotation>
        <appinfo>
            <targetCodeList xmlns="http://www.opengis.net/gml/3.3/exr">FurnitureType</targetCodeList>
        </appinfo>
    </annotation>
</element>
~~~

or in the form 
~~~ xml
<element name="type" type="ex:FurnitureTypeType"/>
~~~
which, however, requires the code list to be encoded inside the XML schema document.

The type gml:ReferenceType is defined as:
~~~ xml
<complexType name="ReferenceType">
    <sequence/>
    <attributeGroup ref="gml:OwnershipAttributeGroup"/>
    <attributeGroup ref="gml:AssociationAttributeGroup"/>
</complexType>
~~~

The content type is empty, this means the element <type> is not allowed any more to contain content, only attributes from the attribute groups are allowed. This will result e.g. in the following representation:
~~~ xml
<Furniture>
    <type xlink:href="www.codelist.org/Furniture#stationary" xlink:title="stationary"/>
</Furniture>
~~~

**Comment by 3DXScape** [comment]
[CodeListCityGML3.0-2019.05.29.pdf](https://github.com/opengeospatial/CityGML-3.0CM/files/3239537/CodeListCityGML3.0-2019.05.29.pdf)
Updated but not yet complete codelist document.

**Comment by 3DXScape** [comment]
[CodeListCityGML3.0-2019.06.12.pdf](https://github.com/opengeospatial/CityGML-3.0CM/files/3284962/CodeListCityGML3.0-2019.06.12.pdf) proposal at end of document.

**Comment by 3DXScape** [comment]
After further discussion in the Modelling Subgroup, the recommendation for CityGML 3.0 is 
# CodeLists

1. CodeList values shall be expressed as UML enumerations in the Conceptual Model within a UML class given the CodeList stereotype.
2. The enumerated CodeList values shall consist of *strings* which are regular expressions (including explicit fixed values). *Note: the use of regular expressions not fully discussed.*
3. Values appearing in an encoded instance must either match a regular expression appearing in the enumeration or appear in an External Source that replaces that enumeration.
4. If an External Source is used, then the values in the External Source shall replace any values present in the UML enumeration.
5. Encoded values from an External Source must include the URI for the external source. How this is done is defined by an encoding specification and mst follw rules and conventions of the encoding language. For example, an XML-encoded codelist value might have an element attribute specifying the URI defining the source or codespace for that source.
6. Regardless of the method of encding vales from an External Source, the absence of a specification of an External Source implies that the codelist value must be present in the enumeration in the UML specification.
7. Any attribute defined with the Codelist stereotype may be replaced by an External Source.
8. The standard does not provide a normative list of External Sources.

**Comment by 3DXScape** [comment]
The suggestion was made by Heidi Vanparys at the Leuven SWG meeting that the current INSPIRE model is along these lines except that instead of recording the initial/suggested/default values in a UML enumeration, these values are simply placed in a [non-normative] table in the standard.

**Comment by 3DXScape** [comment]
ShapeChange issue 189 addresses this issue. There if the class is given the stereotype codelist, an enumeration should be treated as a codelist, not an enumeration.

**Comment by heidivanparys** [comment]
> [... ] that the current INSPIRE model is along these lines except that instead of recording the initial/suggested/default values in a UML enumeration, these values are simply placed in a [non-normative] table in the standard.

![image](https://user-images.githubusercontent.com/11427611/60710432-ffb83200-9f12-11e9-9678-e3511327e42f.png)

![image](https://user-images.githubusercontent.com/11427611/60710489-1f4f5a80-9f13-11e9-8b22-6d8581d99589.png)

The registry: http://inspire.ec.europa.eu/codelist/

[D2.5] DRAFTING TEAM “DATA SPECIFICATIONS.” D2.5: Generic Conceptual Model, Version 3.4 [online]. 8 April 2014. Available from: http://inspire.ec.europa.eu/documents/inspire-generic-conceptual-model

Other sources on codelists:

ELF WP2. ELF codelists [online]. October 2014. Available from: http://elfproject.eu/sites/default/files/ELF%20codelists.pdf

PARSLOW, Peter (ed.). GML Design Policy [online]. Ordnance Survey, December 2015. Available from: https://www.ordnancesurvey.co.uk/about/governance/policies/gml-design.html

Best Practices for registers and registries & Technical Guidelines for the INSPIRE register federation: https://inspire.ec.europa.eu/id/document/tg/registers-and-register-federation

**Comment by heidivanparys** [comment]
> 1. CodeList values shall be expressed as UML enumerations in the Conceptual Model within a UML class given the CodeList stereotype.
> 2. The enumerated CodeList values shall consist of *strings* which are regular expressions (including explicit fixed values). *Note: the use of regular expressions not fully discussed.*
> 3. Values appearing in an encoded instance must either match a regular expression appearing in the enumeration or appear in an External Source that replaces that enumeration.
> 4. If an External Source is used, then the values in the External Source shall replace any values present in the UML enumeration.
> 5. Encoded values from an External Source must include the URI for the external source. How this is done is defined by an encoding specification and mst follw rules and conventions of the encoding language. For example, an XML-encoded codelist value might have an element attribute specifying the URI defining the source or codespace for that source.
> 6. Regardless of the method of encding vales from an External Source, the absence of a specification of an External Source implies that the codelist value must be present in the enumeration in the UML specification.
> 7. Any attribute defined with the Codelist stereotype may be replaced by an External Source.
> 8. The standard does not provide a normative list of External Sources.

For dicussion: a proposal for updated principles for the CityGML 3.0 specification:
1. An enumeration may be used as the value domain of a property if all of the following are true:
  * no changes to the value domain are expected during the lifetime of the schema version and
  * the value domain is normative
2. A code list shall be used as the value domain of a property if one or more of the following are true:
  * changes to the value domain are expected during the lifetime of the schema version
  * the value domain is informative
  * the value domain is normative, already managed by an authority and already published online in a suitable encoding
3. A code list shall be modelled in the UML model using the `<<CodeList>>` stereotype.
4. A code list shall have a tagged value "asDictionary" that is set to "true".
5. A code list shall be modelled in the UML model without values.
6. A code list shall have a tagged value "codeList" that is set to the URI of the resource that specifies the code list if the code list is normative.
7. A (new) code list shall be published on the [OGC definitions server](http://www.opengis.net/def).
8. A property having a code list as value domain shall have a tagged value "defaultCodeSpace" that is set to the URI of the resource that specifies the code list if one of the following is true:
  * a normative code list has been specified
  * an informative code list has been specified 

Note to 2, last bullet:
An example may be TopologicRelationType, where the work from GeoSPARQL may be reused, see e.g. http://www.opengeospatial.org/standards/geosparql, http://www.opengis.net/def/function/geosparql , http://www.opengis.net/def/function/geosparql/ehCovers , http://schemas.opengis.net/geosparql/1.0/geosparql_vocab_all.rdf .

Note to 4:
For GML: see also conversion rule [rule-xsd-cls-codelist-asDictionary](https://shapechange.net/targets/xsd/gml/#rule-xsd-cls-codelist-asDictionary).

Note to 5:
This means that the code list is empty. This emphasizes the fact the code lists are managed outside the application schema.

Note to 7:
> Code lists managed by a single external authority may carry a tagged value “codeList” whose value references the actual external code list. If the tagged value is set, only values from the referenced code list are valid.
> The value of the tagged value “codeList” should be a persistent URI identifying the code list.)
> [ISO 19103]

For GML: see also conversion rule [rule-xsd-prop-targetCodeListURI](https://shapechange.net/targets/xsd/extensions/#rule-xsd-prop-targetCodeListURI).

Note to 8:
So only if no informative code list has been specified, "defaultCodeSpace" is not present (if this situation can occur?).

See also conversion rule [rule-xsd-prop-defaultCodeSpace](https://shapechange.net/targets/xsd/gml/#rule-xsd-prop-defaultCodeSpace).

**Requirement** for external code list:
An external code list shall be available via a resolvable URI.
Note: A value of an external code list may be available via a resolvable URI.

GML encoding rule:
```xml
<EncodingRule name="citygml" extends="iso19136_2007"><!-- instead of gml33 -->
  <rule name="rule-xsd-cls-codelist-asDictionary"/>
  <rule name="rule-xsd-prop-defaultCodeSpace"/>
  <rule name="rule-xsd-prop-targetCodeListURI"/>
  <rule name="rule-xsd-rel-association-classes"/>
  <!-- ... -->
</EncodingRule>
```

So the GML application schemas use gml:CodeType (and not gml:ReferenceType):
```xml
<element name="type" type="gml:CodeType">
	<annotation>
		<appinfo>
			<gml:defaultCodeSpace>http://www.opengis.net/def/path/to/furnituretype/codelist</gml:defaultCodeSpace>
		</appinfo>
	</annotation>
</element>
```

An instance could then look like:
```xml
<Furniture>
    <type>stationary</type>
</Furniture>
```

which means the same as
```xml
<Furniture>
    <type codeSpace="http://www.opengis.net/def/path/to/furnituretype/codelist">stationary</type>
</Furniture>
```

An instance using an external code list must specify the codeSpace attribute:
```xml
<Furniture>
    <type codeSpace="http://www.myorg.net/path/to/other/furnituretype/codelist">some other type of furniture</type>
</Furniture>
```

**Comment by clausnagel** [comment]
I like this proposal, also because it’s very close to CityGML 2.0 and hence allows for continuing to use code lists that have already been defined for CityGML.

One question that comes to my mind: what are the consequences of a “normative“ code list? Am I only allowed to pick the value of the property from this code list? Or could the value still come from another code list if it is referenced using „codeSpace”?

**Comment by 3DXScape** [comment]
I think the only normative lists should be enumerations with values defined in our UML model. All external lists are outside our control. If we want to exactly use values from an external authority and denote those values as normative, we should copy them into a UML enumeration, with an explicit citation as to the source.

**Comment by heidivanparys** [comment]
> One question that comes to my mind: what are the consequences of a “normative“ code list? Am I only allowed to pick the value of the property from this code list? Or could the value still come from another code list if it is referenced using „codeSpace”?

What I meant here was a code list that is normative according to the CityGML specification, and one would indeed only be allowed to pick a value from that list.

A specific case I had in mind here was the TopologicRelationType. But another solution for that one could indeed be to have it as an enumeration.

**Comment by 3DXScape** [comment]
My comment was on that point - if it is normative, it should be an enumeration. The principle is that  a developer can know required (i.e. normative) attribute values in advance from the CityGML standard.

**Comment by heidivanparys** [comment]
From the presentation of yesterday:

**Principles for modeling**:
1. An enumeration shall be used as the value domain of a property if the value domain is normative.
2. A code list shall be used as the value domain of a property if that value domain is informative.
3. A code list shall be modelled in the UML model using the `<<CodeList>>` stereotype.
4. A code list shall have a tagged value "asDictionary" that is set to "true".
5. A code list shall be modelled in the UML model without values.
6. A property having a code list as value domain shall have a tagged value "defaultCodeSpace" that is set to the URI of the resource that specifies the code list.

**Principles for publication of code lists**:
1. A code list defined by the CityGML SWG shall be published online. 
2. A code list defined by the CityGML SWG should be published on the [OGC Definitions Server](http://www.opengis.net/def/).
3. A code list defined by an external party shall be published online.

Note to 3: A value of a code list may have a URI, but this is no requirement. Only the code list itself must have a URI.

**GML encoding rule**:
Based on GML 3.2:

```xml
<EncodingRule name="citygml" extends="iso19136_2007">
  <rule name="rule-xsd-rel-association-classes"/>
  <!-- ... -->
</EncodingRule>
```

Note 1: iso19136_2007 already includes:
`rule-xsd-cls-codelist-asDictionary`
`rule-xsd-prop-defaultCodeSpace`

Note 2: `rule-xsd-rel-association-classes` is from GML 3.3.

**Comment by thomashkolbe** [comment]
As this was consensus in the last meeting of the CityGML SWG modeling subgroup as well as in the CityGML SWG at the last TC meeting in Banff, we should close it in the next telcon.

**Comment by TatjanaKutzner** [comment]
I implemented now the code lists in the UML model by defining an empty code list class for every code list and changing the attribute types from `Code` to the corresponding code list class. 

I also changed the encoding rule in the ShapeChange configuration file and derived new GML application schemas.
