### ISSUE TITLE
Rename attribute "uri" to "target" in class "TextureAssociation"

### ISSUE THREAD

**Issue by TatjanaKutzner** [opengeospatial/CityGML-3.0CM#105]
The class `TextureAssociation` contains an attribute `uri` that specifies an URI that points to the surface geometry object to which the texture is applied.

Similarly, the classes `X3DMaterial` and `GeoreferencedTexture` define an attribute `target` that also specifies an URI that points to the surface geometry object to which the texture is applied.

Thus, I suggest to rename the attribute `uri` to `target` to have a consistent naming in all three classes.

**Comment by TatjanaKutzner** [comment]
After discussion within the CityGML Modelling Subgroup we decided that it makes sense to rename the attribute to `target`. 

In CityGML 2.0, the attribute was named `uri`, because the name `target` was already used as role name for the association between `ParameterizedTexture` and `TextureParameterization`. 
In CityGML 3.0, a different naming convention is used for role names. The new role name is now `textureParameterization`. Thus, renaming the attribute is possible and makes sense.

**Comment by clausnagel** [comment]
+1

**Comment by clausnagel** [comment]
Solved in 7b997d4d95f800a8882c6c75524326754cf1c4ca
