### ISSUE TITLE
Feature Type Door class - Construction package: change the type of the properties prefixes to Door (instead of Window)

### ISSUE THREAD

**Issue by EmDevys** [opengeospatial/CityGML-3.0CM#106]
Presently, for the class Feature Type Door class, the class / usage / function properties have types prefixed by Window. They should have types prefixed by Door (e.g. DoorClassValue instead of WindowClassValue for class property/attribute.

**Comment by TatjanaKutzner** [comment]
Thanks for the comment. I just corrected it in the UML model.

**Comment by clausnagel** [comment]
Solved in 7b997d4d95f800a8882c6c75524326754cf1c4ca
