### ISSUE TITLE
Editorial comments to the draft specification document

### ISSUE THREAD

**Issue by nob140** [opengeospatial/CityGML-3.0CM#115]
Thanks for your great efforts in preparing the draft specification document!
I reviewed the draft until chapter 8.2 and have several editorial comments.
May I provide all comments here in one issue?
Please let me know if I should post these comments separately or post to ML.
I hope this issue could help for finalizing the draft successfully!

pp.6
TC211 -> ISO/TC211 [the same hereinafter]

pp.9
pedes-trian -> pedestrian
sustain-able -> sustainable
securi-ty -> security

small regions and can represent
-> small regions, and can represent
[easy for non-native readers!]

differenti-ations -> differentiations
GI systems -> "Geospatial Information systems" or "Geographic Information Systems" or GI should be defined in 5.1

allowing the possibility of selling the same data to customers from different application fields
-> [Is it possible to mention the merits not only for data providers but also for data users such as government?]

CityGML v2.0 -> CityGML 2.0 [the same hereinafter]
CityGML v3.0 -> CityGML 3.0 [the same hereinafter]

pp.10
i3S -> i3s
3D tiles -> 3D Tiles
Portrayal 3D Portrayal Service -> 3D Portrayal Service

pp.10-11 "Features of the CityGML v3.0 Conceptual Model:"
How about mentioning the new concepts such as Dynamizer and Versioning?
Or should include all new concepts such as PointCloud and Construction?

pp.13
12-019 -> 20-010 (?)

Should ISO 19108 be added since TM_Position is used?
Is ISO 8601 needed in this CM specification?

pp.14
this Best Practice -> this specification

pp.16-17
BIM, GI should be added.
Level of Detail -> Levels of Detail [the same hereinafter]
TC211 -> ISO/TC211 [the same hereinafter]

pp.20
In the context of this standard this only applies
-> In the context of this standard, this only applies

pp.21
ISO 19101 -> [delete link, or link to correct reference]

pp.25
levels of detail -> "Levels of Detail" of "LOD" [the same hereinafter]
bitemporal -> bi-temporal [the same hereinafter]

pp.26
Building, Tunnel, WaterBody -> [Italic]
AnyFeature -> [Italic]

pp.27
level of detail -> Levels of Detail
With only a few exceptions all geometries -> With only a few exceptions, all geometries
B-splines or clothoids or curved surfaces -> B-splines or clothoids, or curved surfaces

pp.28
A geometry defining -> For example, a geometry defining
aggregate touching -> aggregate, touching [is it correct?]
Section 8.2.4 -> Section 8.4

pp.29
Core -> [Italic]
BIM each -> BIM, each
CRS the -> CRS, the
3D coordinate reference systems (CRS) -> "3D CRS" or "3D coordinate reference systems"

pp.30
virtual boundaries and -> virtual boundaries, and

pp.31
Core, Building, Relief, WaterBody -> [Italic]

pp.32
[Question: Though Roads are UnoccupiedSpaces,
I understand that the surface normals should be directed towards the observer.
Is it correct to apply the opposite direction to Roads?]

pp.33, 34
Löwner et al. 2016 -> [link to correct reference]
application domain extensions -> Application Domain Extensions

pp.35
(right, white) -> (right, red)

pp.36
appearance and all -> appearance, and all

pp.37
Versioning, Dynamizer -> [Italic]

pp.39
In practical applications the -> In practical applications, the
provides two different concepts -> provides three different concepts

pp.41
http://www.opengis.net/spec/CityGML/3.0/req/req-class-core
-> http://www.opengis.net/spec/CityGML-1/3.0/req/req-class-core [?]

ISO 191** -> [be consistent with the terms, ISO 191XX or ISO 19100 series?]
Level Of Detail -> Levels of Detail
Types, Enumerations and Codelist ->  [link to 8.2.7]

pp.43
convinence -> convenience

[Figure 13]
ISO 19111 -> ISO 19111:2019
from ISO TC211 -> from ISO 19111 All [correct?]

[Table 4]
undefined -> [should be defined?]

pp.44
[Figure 14]
[Arrow under the AbstractFeatureWithLifespan should be modified?]

pp.46
[Question: Are there any figures about the AbstractSpaceBoundary and AbstractLogicalSpace in this specification? Those figures will help readers to understand new concepts. Or is it possible to add an explanation of SpaceBoundary to Figure 16?]

pp.47
[Figure 17]
[Maybe AbstractFeatureWithLifespan and CityModel are not needed here.]

pp.48
Level of Detail -> Levels of Detail

pp.49
[The items of Table 7 should be the same in Figure 18]
AbstractPointCloud and AbstractSpaceBoundary should be deleted from Table 7, and AbstractPointCloud should be moved to Table 8.

pp.51
[Table 8 should include AbstractPointCloud.]

pp.55
CityGML Users Guide -> [link to correct guide]

**Comment by nob140** [comment]
pp.39
provides two different concepts -> provides three different concepts
And adding the code lists [same as Chapter 10.]

**Comment by 3DXScape** [comment]
Thanks for your detailed review! These issues split into categories and added to 117, 118, and 119.
