### ISSUE TITLE
Editorial comments again

### ISSUE THREAD

**Issue by nob140** [opengeospatial/CityGML-3.0CM#116]
Dear Editors,

I would like to provide editorial comments again.
BTW, I found several inconsistencies between Section 8 UML diagrams, Section 9 Data Dictionary, and schema files.
For example, featuerID, identifies, name, and description in AbstractFeature are not defined in cityGMLBase.xsd.
I understand that the schema files are not normative, so I have reviewed only UML diagrams and Data Dictionaries.

8.2 Figure 17, 19
Is the role "bounds" correct at the one direction association between AbstractSpace and AbstractSpaceBoundary?
There is only "boundary" in AbstractSpaceType in pp.121, and no "bounds" in AbstractSpaceBoundaryType in pp.122.

8.3 Appearance
In the Dependency, should X3D be added maybe?

8.6
pp.65 "sensor or thing and its" -> "sensor or thing, and its"
pp.66 "For each TimeValuePair only" -> "For each TimeValuePair, only"

8.7
pp.67 "type String, Integer, Double, Date, URI, and Measure" -> "type String, Integer, Double, Date, URI, Measure, and Code"

8.8
pp.70 "recreational objects and objects" -> "recreational objects, and objects"

pp.72 "having a specific land cover with or without vegetation, such as sand, rock, mud flats, forest, or grasslands."
-> "having a specific land cover" [I guess examples are not needed again here.]
or "having a specific land cover with or without vegetation, such as sand, rock, mud flats, forest, grasslands, or wetlands" [same as pp.71]

8.9
pp.72 [Question] I would like to confirm how PointCloud can be used in CityFurniture. Does that mean as ImplicitGeometry?

8.10
"a.k.a." -> "also known as" [the same hereinafter]
pp.75 8.10.2 Table 35 AbstractReliefComponent:
"a TIN, a Grid, mass points" -> "a TIN, a raster or grid, mass points" [It may be not clear for readers that the Grid indicates RasterRelief.]

8.11
Since granularity is new concept and overall transportation concepts are relatively complicated, it may be better to add an example figure here. A simple figure such as Figure 6 or 15 may be enough.
pp.79 "ADEOfAuxiliaryTrafficAra" -> "ADEOfAuxiliaryTrafficArea"
pp.81-82 Are TransportationSpaceClassValue, TransportationSpaceFunctionValue, and TransportationSpaceUsageValue correct? I couldn't find them in Figure 28.

8.13
Since Versioning is new concept, it may be better to add an example figure here. A simple figure such as Figure 6 or 15 may be enough.

pp.85
"bitemporal" -> "bi-temporal"

"This allows for providing all objects with information on the time period a specific version of an object is an integral part of the 3D city model and on the lifespan a specific version of an object exists in the real world."
-> "This allows for providing all objects with information, on the time period a specific version of an object is an integral part of the 3D city model, and on the lifespan a specific version of an object exists in the real world." [correct? Figure is needed...]

8.14
In Figure 31, is ClosureSurface needed here?

8.15
Dependency: Is "/req/req-class-generics" mandatory?
pp. 90, 92 "earth and are" -> "earth, and are"

8.17
Since Storey is new concept, it may be better to add an example figure here to explain the concept of horizontal and vertical subdivision. A simple figure such as Figure 6 or 15 may be enough.
pp.99 "building parts and logically" -> "building parts, and logically"

8.18
pp.104
"goods" -> "things"
"disaster management or" -> "disaster management, or"

9.1
Definition: How about adding short definitions at least to the main part in all tables?
All ISO classes used in this specification should be added such as GM_MultiPoint and TM_Position.

9.1.3 Which Figure 6? It should be linked.

9.1.6 Which Figure 9? It should be linked.
Is "GM_Point::position [1] : DirectPosition" needed?

9.1.7 Which Figure 13? It should be linked.

9.1.8 Which Figure 12? It should be linked.
What is the meaning of "Target class and multiplicity" and why only "Building" is mentioned here?

9.1.9 Which Figure 21 and 22? They should be linked.

9.1.10 Which Figure 21? It should be linked.

9.2
"The Core module defines abstract base classes"
-> "Those include abstract base classes" [grammatically correct?]

pp.125 Address:
The link to GM_MultiPoint should be added.
Table 4 in pp.43 should include GM_MultiPoint.

pp.125 CityModel:
EngineeringCRS should be described more,
maybe adding link to the CityGML Users Guide?

pp.133 Occupancy:
I think the Occupancy is not shown in any UML diagrams in Section 8.2, though shown in 8.11 as blue-colored.
Maybe the Occupancy should be added to Figure 19
or the UML diagram in eap file "Core - Basic Types, Enumarations, Code lists, Class Diagram" should be added to 8.2.7?
[I would apologize if it is already shown in some UML diagrams in 8.2.]

9.6
pp.165 mqttTopic needs an explanation such as "This attribute is relevant when the MQTT Protocol is used."
pp.166 "For each TimeValuePair only" -> "For each TimeValuePair, only"
pp.167 TM_Position should be linked.

9.7
pp.175 ISO 19103 should be linked.

9.8
pp.179 "forest, or grasslands." -> "forest, grasslands, or wetlands" [same as pp.71]

9.9
GM_MultiPoint should be linked.

9.10
pp.183 "a TIN, a Grid, mass points" -> "a TIN, a raster or grid, mass points" [same as 8.10]

9.11
pp.190, 197 granularity:
"desired level of detail" -> "desired level of granularity" [correct?]
pp.199 "ADEOfAuxiliaryTrafficAra" -> "ADEOfAuxiliaryTrafficArea"
pp.207-208 Are TransportationSpaceClassValue, TransportationSpaceFunctionValue, and TransportationSpaceUsageValue correct? [same as 8.11]

9.15
pp.222 "earth and are" -> "earth, and are" [same as 8.15]
pp.238 elevationValue:
"DirectPoisition" should be defined maybe in 9.1 or 9.2, and linked. [I want to know the meaning of "value".]

9.17
pp.259 In BuildingUnit, the role "storey" in Figure 34 is not defined. Which is correct?
pp.261
ADEOfBuildingRoom: "None>" -> "None"
ADEOfBuildingUnit: The font of the Definition should be changed. [should be moved next row?]
pp.262 RoomHeight: "<←section,>>" -> [?]

10.3
pp.280 Figure:
The figure should have a figure number and title.
The text "(from Building)" and arrow should not be overlapped.

Annex D
INSPIRE document should be included here (or maybe in Chapter 4?) and referred from links in document.

Annex A-C
[Not yet reviewed. I hope I have enough time to review them before July 1st...]

**Comment by 3DXScape** [comment]
All of these were split into issues 117, 118, and 119, according to type of attention required. Can be closed, Nobu?

**Comment by nob140** [comment]
Dear Steve,

Great, thanks!
Could you close them?
Or please let me know if I  should close.

Best Regards,
Nobu


2020年7月2日木曜日 Steve Smyth <notifications@github.com>:

**Comment by 3DXScape** [comment]
These issues split into categories and added to 117, 118, and 119.
