### ISSUE TITLE
CityGML 3 Draft Review by 石丸伸裕 : Typographical and Grammatical Issues

### ISSUE THREAD

**Issue by 3DXScape** [opengeospatial/CityGML-3.0CM#118]
In my opinion, these 54 issues relate to typographical or grammatical or similar editing errors that can be resolved by the original author(s) or one of the other editors.

Nobu_T_1: pp.6
- [x] TC211 -> ISO/TC211 [the same hereinafter]

Nobu_T_2: pp.9
- [x] pedes-trian -> pedestrian
- [x] sustain-able -> sustainable
- [x] securi-ty -> security

Nobu_T_3: 
- [x] small regions and can represent -> small regions, and can represent [easy for non-native readers!]

Nobu_T_4: 
- [x] differenti-ations -> differentiations
- [x] GI systems -> "Geospatial Information systems" or "Geographic Information Systems" or GI should be defined in 5.1

Nobu_T_5: 
- [x] CityGML v2.0 -> CityGML 2.0 [the same hereinafter]
- [x] CityGML v3.0 -> CityGML 3.0 [the same hereinafter]

Nobu_T_6: pp.10
- [x] i3S -> i3s
- [x] 3D tiles -> 3D Tiles
- [x] Portrayal 3D Portrayal Service -> 3D Portrayal Service

Nobu_T_7: pp.13
- [x] 12-019 -> 20-010 (?)

Nobu_T_8: pp.16-17
- [x] BIM, GI should be added.
- [x] Level of Detail -> Levels of Detail [the same hereinafter]
- [x] TC211 -> ISO/TC211 [the same hereinafter]

Nobu_T_9: pp.20
- [x] In the context of this standard this only applies -> In the context of this standard, this only applies

Nobu_T_10: pp.21
- [x] ISO 19101 -> [delete link, or link to correct reference]

Nobu_T_11: pp.25
- [x] levels of detail -> "Levels of Detail" of "LOD" [the same hereinafter]
- [x] bitemporal -> bi-temporal [the same hereinafter

Nobu_T_12: pp.26
- [x] Building, Tunnel, WaterBody -> [Italic]
- [x] AnyFeature -> [Italic]

Nobu_T_13: pp.27
- [x] level of detail -> Levels of Detail
- [x] With only a few exceptions all geometries -> With only a few exceptions, all geometries
- [x] B-splines or clothoids or curved surfaces -> B-splines or clothoids, or curved surfaces

Nobu_T_14: pp.28
- [x] A geometry defining -> For example, a geometry defining
- [x] aggregate touching -> aggregate, touching [is it correct?]
- [x] Section 8.2.4 -> Section 8.4

Nobu_T_15: pp.29
- [x] Core -> [Italic]
- [x] BIM each -> BIM, each
- [x] CRS the -> CRS, the
- [x] 3D coordinate reference systems (CRS) -> "3D CRS" or "3D coordinate reference systems"

Nobu_T_16: pp.30
- [x] virtual boundaries and -> virtual boundaries, and

Nobu_T_17: pp.31
- [x] Core, Building, Relief, WaterBody -> [Italic]

Nobu_T_18: pp.33, 34
- [x] Löwner et al. 2016 -> [link to correct reference]
- [x] application domain extensions -> Application Domain Extensions

Nobu_T_19: pp.35
- [x] (right, white) -> (right, red)

Nobu_T_20: pp.36
- [x] appearance and all -> appearance, and all

Nobu_T_21: pp.37
- [x] Versioning, Dynamizer -> [Italic]

Nobu_T_22: pp.39
- [x] In practical applications the -> In practical applications, the
- [x] provides two different concepts -> provides three different concepts

Nobu_T_23: pp.41
- [x] http://www.opengis.net/spec/CityGML/3.0/req/req-class-core -> http://www.opengis.net/spec/CityGML-1/3.0/req/req-class-core [?]

Nobu_T_24: 
- [x] ISO 191** -> [be consistent with the terms, ISO 191XX or ISO 19100 series?]
- [x] Level Of Detail -> Levels of Detail
- [x] Types, Enumerations and Codelist -> [link to 8.2.7]

Nobu_T_25: pp.43
- [x] convinence -> convenience

Nobu_T_26: [Figure 13]
- [x] ISO 19111 -> ISO 19111:2019
- [x] from ISO TC211 -> from ISO 19111 All [correct?]

Nobu_T_27: pp.44
- [x] [Figure 14] [Arrow under the AbstractFeatureWithLifespan should be modified?]

Nobu_T_28: p.47
- [x] [Figure 17] [Maybe AbstractFeatureWithLifespan and CityModel are not needed here.]

Nobu_T_29: pp.48
- [x] Level of Detail -> Levels of Detail

Nobu_T_30: pp.39
- [x] provides two different concepts -> provides three different concepts
- [x] And adding the code lists [same as Chapter 10.]

Nobu_T_31: 8.6
- [x] pp.65 "sensor or thing and its" -> "sensor or thing, and its"
- [x] pp.66 "For each TimeValuePair only" -> "For each TimeValuePair, only"

Nobu_T_32: 8.7
- [x] pp.67 "type String, Integer, Double, Date, URI, and Measure" -> "type String, Integer, Double, Date, URI, Measure, and Code"

Nobu_T_33: 8.8
- [x] pp.70 "recreational objects and objects" -> "recreational objects, and objects"

Nobu_T_34: pp.72 
- [x] "having a specific land cover with or without vegetation, such as sand, rock, mud flats, forest, or grasslands."
-> "having a specific land cover" [I guess examples are not needed again here.]
or "having a specific land cover with or without vegetation, such as sand, rock, mud flats, forest, grasslands, or wetlands" [same as pp.71]

Nobu_T_35: 8.10
- [x] "a.k.a." -> "also known as" [the same hereinafter]
- [x] pp.75 8.10.2 Table 35 AbstractReliefComponent: "a TIN, a Grid, mass points" -> "a TIN, a raster or grid, mass points" [It may be not clear for readers that the Grid indicates RasterRelief.]

Nobu_T_36: pp.85
- [x] "bitemporal" -> "bi-temporal"

Nobu_T_37: 
- [x] "This allows for providing all objects with information on the time period a specific version of an object is an integral part of the 3D city model and on the lifespan a specific version of an object exists in the real world."
-> "This allows for providing all objects with information, on the time period a specific version of an object is an integral part of the 3D city model, and on the lifespan a specific version of an object exists in the real world." [correct? Figure is needed...]

Nobu_T_38: 8.15
- [x] pp. 90, 92 "earth and are" -> "earth, and are"

Nobu_T_39: 8.18 pp.104
- [x] "goods" -> "things"
- [x] "disaster management or" -> "disaster management, or"

Nobu_T_40: 9.1.3 
- [x] Which Figure 6? It should be linked.

Nobu_T_41: 9.1.6 
- [x] Which Figure 9? It should be linked.
- [x] Is "GM_Point::position [1] : DirectPosition" needed?

Nobu_T_42: 9.1.7 
- [x] Which Figure 13? It should be linked.

Nobu_T_43: 9.1.8 
- [x] Which Figure 12? It should be linked.

Nobu_T_44: 9.1.9 
- [x] Which Figure 21 and 22? They should be linked.

Nobu_T_45: 9.1.10 
- [x] Which Figure 21? It should be linked.

Nobu_T_46: 9.2
- [x] "The Core module defines abstract base classes" -> "Those include abstract base classes" [grammatically correct?]

Nobu_T_47: pp.125 
- [x] Address: The link to GM_MultiPoint should be added.
- [x] Table 4 in pp.43 should include GM_MultiPoint.

Nobu_T_48: 9.7
- [x] pp.175 ISO 19103 should be linked.

Nobu_T_49: 9.8
- [x] pp.179 "forest, or grasslands." -> "forest, grasslands, or wetlands" [same as pp.71]

Nobu_T_50: 9.9
- [x] GM_MultiPoint should be linked.

Nobu_T_51: 9.10
- [x] pp.183 "a TIN, a Grid, mass points" -> "a TIN, a raster or grid, mass points" [same as 8.10]

Nobu_T_52: 9.11
- [x] pp.190, 197 granularity: "desired level of detail" -> "desired level of granularity" [correct?]
- [x] pp.199 "ADEOfAuxiliaryTrafficAra" -> "ADEOfAuxiliaryTrafficArea"
- [x] pp.207-208 Are TransportationSpaceClassValue, TransportationSpaceFunctionValue, and TransportationSpaceUsageValue correct? [same as 8.11]

Nobu_T_53: 10.3 pp.280 Figure:
- [x] The figure should have a figure number and title.
- [x] The text "(from Building)" and arrow should not be overlapped.

Nobu_T_54: Annex D
- [x] INSPIRE document should be included here (or maybe in Chapter 4?) and referred from links in document.

**Comment by cmheazel** [comment]
@TatjanaKutzner Most of these issues are editorial.  However some MAY impact the UML model so I have tagged this issue accordingly.

**Comment by cmheazel** [comment]
Re. Nobu_T_8 - BIM: I'm not sure what is being asked for here.
Re. Nobu_T_11 - Bitemporal: Bitemporal is the term used in the academic literature (see Johnson, Tom 2014) 
Re. Nobu_T_11 - Levels of Detail: Capitalization has been used where the LOD concept is being referred to.

**Comment by TatjanaKutzner** [comment]
The following sub-issues have been implemented in the UML model:
T_31, T_34, T_35 (second point only), T_46, T_49, T_51, and T_52

The other sub-issues do not require updates to the UML model.

**Comment by TatjanaKutzner** [comment]
Re T_26:
The suggested changes are correct. However, currently the text is taken automatically from the ISO packages. 
I can chose from the following ISO packages:
![grafik](https://user-images.githubusercontent.com/5949401/92117973-2b27fc80-edf6-11ea-944f-fcbba1f07f54.png)
At the moment, I use the topmost package. It probably needs to be changed to ISO 19111 Edition 3, as this is the most current specification.

I'll change it in the UML model.
After changing it looks like this in the UML model:
![grafik](https://user-images.githubusercontent.com/5949401/92118925-624add80-edf7-11ea-9d60-69685d813d33.png)

**Comment by TatjanaKutzner** [comment]
Re T_27:
I cannot solve this problem in the UML model, because there the arrows look correct. 
@cmheazel Maybe the problem arises when exporting the image from the UML model?

**Comment by cmheazel** [comment]
@TatjanaKutzner I assume the issue is the skewed arrow on the generalization relationships between AbstractFeatureWithLifespan and its' subclasses. If so, my version of EA looks the same as the PDF. Do you want me to fix it?

**Comment by TatjanaKutzner** [comment]
@cmheazel: Yes, it's the skewed arrow. Please fix it in your EA version, as in my EA version it looks correct.

**Comment by cmheazel** [comment]
@TatjanaKutzner The updated figure is a little better. there are a number of associations all coming together at the same point. Hard to get the arrows in perfect alignment.

**Comment by TatjanaKutzner** [comment]
T_8: I added BIM to the list of abbreviated terms, but did not add GI, as it is not used anywhere in the document
T_28: AbstractFeatureWithLifespan and CityModel are not required in figure 17. They are already introduced in figure 14 and do not give additional information to figure 17.
T_53: The figure has now a figure number and title. I suggest to keep the arrow as it is. The text cannot be moved, only the arrow. But moving the arrow to the right or left end of the box also looks strange.
T_54: Chapter 4 includes now the INSPIRE specification on buildings. Referencing still needs to be done.

T_23, T_40-T_45, T_47, T_48, and T_50: These items need to be solved in the template and/or directly in the tables of chapter 9.

**Comment by cmheazel** [comment]
9.1.3, 9.1.6, 9.1.7, 9.1.8, 9.1.9, 9.1.10 - These references appear in the definitions extracted from the TC211 Harmonized Model. The figures they reference are in the ISO standards documents. Since the ISO documents are not web accessible, these references have been removed.

**Comment by cmheazel** [comment]
Should we add the following ISO classes:
DirectPosition
GM_MultiPoint
TM_Position

**Comment by cmheazel** [comment]
9.7 - the reference to ISO 19103 occurs within a definition exported from the TC211 Harmonized UML model. We prefer to limit our editing of exported content as much as possible.

**Comment by cmheazel** [comment]
P41 - All instances have been corrected to CityGML-1/3.0.

**Comment by TatjanaKutzner** [comment]
Table 5 (was previously table 4) and chapter 9.1 list all ISO classes that are explicitly used in the CityGML UML model.

Since **GM_MultiPoint** is used explicitly in the PointCloud module, also GM_MultiPoint should be added to the table and the chapter.

The same applies to **TM_Position**, as it is used as attribute type in the Dynamizer module, and **DirectPosition**, which is used in the Construction module.

**Comment by cmheazel** [comment]
Added GM_MultiPoint, DirectPosition, and TM_Position. Validated that all links now work.
