### ISSUE TITLE
CityGML 3 Draft Review by 石丸伸裕 : Substantive Editorial Issues

### ISSUE THREAD

**Issue by 3DXScape** [opengeospatial/CityGML-3.0CM#119]
**In my opinion, these 12 issues require decisions or contributions of the original author(s) or the editors as a group.**

Nobu_E_1: pp.49
- [x] [The items of Table 7 should be the same in Figure 18]
- [x] AbstractPointCloud and AbstractSpaceBoundary should be deleted from Table 7, and AbstractPointCloud should be moved to Table 8.

Nobu_E_2: pp.51
- [x] [Table 8 should include AbstractPointCloud.]

Nobu_E_3: pp.55
- [x] CityGML Users Guide -> [link to correct guide]

Nobu_E_4: 8.3 Appearance
- [x] In the Dependency, should X3D be added maybe?In the Dependency, should X3D be added maybe?

Nobu_E_5: 8.17
- [ ] Since Storey is new concept, it may be better to add an example figure here to explain the concept of horizontal and vertical subdivision. A simple figure such as Figure 6 or 15 may be enough.
- [x] pp.99 "building parts and logically" -> "building parts, and logically"

Nobu_E_6: 9.1
- [x] Definition: How about adding short definitions at least to the main part in all tables?
- [x] All ISO classes used in this specification should be added such as GM_MultiPoint and TM_Position.

Nobu_E_7: pp.125 CityModel:
- [x] EngineeringCRS should be described more, maybe adding link to the CityGML Users Guide?

Nobu_E_8: pp.133 Occupancy:
- [x] I think the Occupancy is not shown in any UML diagrams in Section 8.2, though shown in 8.11 as blue-colored.
Maybe the Occupancy should be added to Figure 19 or the UML diagram in eap file "Core - Basic Types, Enumarations, Code lists, Class Diagram" should be added to 8.2.7? [I would apologize if it is already shown in some UML diagrams in 8.2.]

Nobu_E_9: 9.6
- [x] pp.165 mqttTopic needs an explanation such as "This attribute is relevant when the MQTT Protocol is used."
- [x] pp.166 "For each TimeValuePair only" -> "For each TimeValuePair, only"
- [x] pp.167 TM_Position should be linked.

Nobu_E_10: 9.15
- [x] pp.222 "earth and are" -> "earth, and are" [same as 8.15]
- [x] pp.238 elevationValue: "DirectPoisition" should be defined maybe in 9.1 or 9.2, and linked. [I want to know the meaning of "value".]

Nobu_E_11: 9.17
- [x] pp.259 In BuildingUnit, the role "storey" in Figure 34 is not defined. Which is correct?
- [x] pp.261
ADEOfBuildingRoom: "None>" -> "None"
ADEOfBuildingUnit: The font of the Definition should be changed. [should be moved next row?]
pp.262 RoomHeight: "<←section,>>" -> [?]

Nobu_E_12: Annex D
- [x] INSPIRE document should be included here (or maybe in Chapter 4?) and referred from links in document.

**Comment by cmheazel** [comment]
Should we remove references to the Guide until we have a Guide document to point to?

**Comment by TatjanaKutzner** [comment]
Re Nobu_E_8: Yes, the UML diagram "Core - Basic Types, Enumarations, Code lists, Class Diagram" from the EAP project should be added to 8.2.7. It's not only the Occupancy class that is missing, also the other classes should be displayed for better understanding of the UML model.

**Comment by TatjanaKutzner** [comment]
The following sub-issues have been implemented in the UML model:
E_7: The definition has been extended.
E_9 (The first two points only)
E_10 (The first point only)

The other sub-issues do not require updates to the UML model.

**Comment by TatjanaKutzner** [comment]
Re E_4: I think we don't need to add a dependency to X3D. CityGML reuses concepts from X3D and modells them in the CityGML conceptual model, but the CityGML conceptual model does not depend on or refer to a X3D conceptual model.

**Comment by TatjanaKutzner** [comment]
Re E_11 (first point): The role "storey" needs to be defined in BuildingUnit in the data dictionary. The figure is correct. 
@cmheazel: Might be a problem that occurred when deriving the data dictionary? In the UML model it seems to be modelled correctly.

**Comment by cmheazel** [comment]
@TatjanaKutzner The association between BuildingUnit and Storey is bi-directional with Storey being the source and BuildingUnit being the target. I believe this is the only bi-directional association in the model. I also thought we decided not to use bi-directional associations. If that is not the case, then I will have to update the EA templates.

**Comment by 3DXScape** [comment]
Recommended resolution: split the bi-directional BuildingUnit-Storey association into two unidirectional ones. Also need to compare the sub-issues in this issue with the current document and create a new comment with the unresolved items and possible solutions.

**Comment by TatjanaKutzner** [comment]
The bi-directional association is now split up into two uni-directional associations the UML model.

**Comment by TatjanaKutzner** [comment]
E_12: I added the INSPIRE specification on Buildings to Chapter 4. Referencing still needs to be done.
E_5: Requests an additional figure.
E_1, E_2, E_6, E_9, E_10, and E_11: These items need to be solved in the template and/or directly in the tables of chapter 9.

**Comment by cmheazel** [comment]
Nobu_E_1:  AbstractSpaceBoundary has been removed from Table 8 (Geometry). It does not appear in figure 18. However it does appear in figure 17 as well as table 7 (Space). 
AbstractPointCloud does not appear to have a place to reside. As an Abstract CityGML Feature Type it should not in table 9 (other). Yet it only appears in figure 19. Some guidance would be welcome.

**Comment by cmheazel** [comment]
Nobu_E_6, Nobu_E_9, Nobu_E_10: Additional ISO classes - See issue #118

**Comment by TatjanaKutzner** [comment]
E_1: I suggest to add AbstractPointCloud to figure 18 as it is also related to geometry representation.

**Comment by TatjanaKutzner** [comment]
E_1: AbstractPointCloud is now included in figure 18

**Comment by cmheazel** [comment]
Only open issue is inclusion of an example figure for Storey. That recommendation has been documented in issue #156. This issue can now be closed.
