### ISSUE TITLE
CityGML 2.0 conformance requiremet 10.3.8.1 should be removed

### ISSUE THREAD

**Issue by volkercoors** [opengeospatial/CityGML-3.0CM#12]
see Change request 
http://ogc.standardstracker.org/show_request.cgi?id=553#c0
Deprecate CityGML Conformance Requirement 10.3.8.1 Building / Building Part

[CR req 10-3-8-1.pptx](https://github.com/opengeospatial/CityGML-3.0CM/files/2364455/CR.req.10-3-8-1.pptx)

**Comment by TatjanaKutzner** [comment]
This issues was discussed previously already and agreed upon. The conformance requirement will be removed in CityGML 3.0.
