### ISSUE TITLE
CityGML SWG review: abstract

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/CityGML-3.0CM#120]
A few comments on the abstract:

- [ ] This UML model extends → This UML model builds on (or reuses)
- [ ] TC211 → TC 211 (thus including a space; this applies to the whole document)
- [ ] fundation → foundation
- [ ] man-made features → urban features
- [ ] described in the City Models → described in the city models

**Comment by heidivanparys** [comment]
The same comments apply to 1.1 Motivation, as the text in the abstract is repeated there.

**Comment by cmheazel** [comment]
All changes made except for man-made -> urban. This change would imply that CityGML cannot be used for non-urban features such as barns, suburbs, or factories. I don't believe that is our intent.

**Comment by cmheazel** [comment]
Agreed to close at the SWG meeting of 20 August 2020
