### ISSUE TITLE
CityGML SWG review: motivation

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/CityGML-3.0CM#121]
Suggestion 1: change

> Since the limited reusability of models inhibits the broader use of 3D city models, a more general modelling approach had to be taken in order to satisfy the information needs of the various application fields.

to

> Since the limited reusability of models inhibits the broader use of 3D city models **and may not justify the costs associated with maintaining city models**, a more general modelling approach had to be taken in order to satisfy the information needs of the various application fields.

Suggestion 2: change

> allowing the possibility of selling the same data to customers from different application fields

to something like

> allowing governments and companies to reap the benefits of their investment in 3D city models by being able to put the same models into play in different application fields

Suggestion 3: 
* remove the last two paragraphs from this clause
* or remove heading "1.1 Motivation" and only keep "Chapter 1. Introduction"
* or add a heading "1.2" with a title that covers the contents of those two paragraphs ("overall description"?)

In general: think about the order of the sentences, as far as I can see, the following topics are covered, should some of the sentences be moved?

![image](https://user-images.githubusercontent.com/11427611/86108810-efa24680-bac3-11ea-89cb-50358e7bcbf2.png)

Suggestion 4: last line: GI is not defined in 5.1, Abbreviated Terms

Suggestion 5: last sentence: should "either ... or ..." be "both ... and ..."?

**Comment by cmheazel** [comment]
@heidivanparys Your recommended changes have been applied (with a bit of editorial discretion).

**Comment by cmheazel** [comment]
Agreed to close at the SWG meeting of 20 August 2020
