### ISSUE TITLE
definition of "conceptual model" vs "data model"

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/CityGML-3.0CM#124]
At the open OAB meeting, the Architecture Board presented the new OGC definition of "conceptual model", I guess that one should be used in the CityGML standard.

See (in the OGC portal):
- OAB issue 1310
- the revised TC P&P (where to find those? has that action been completed?)
- clauses 6.2 and 6.3 in 19-014r2
- the powerpoint with title "Open OAB Toulouse"

Both "conceptual model" and "data model" are used in the CityGML standard, probably one of those should be used consistently throughout the standard, with one clause explaining what is what (e.g. as in 19-014r2).

**Comment by cmheazel** [comment]
From the OAB Issue Tracker:

Conceptual model: a description of common concepts and their relationships, particularly in order to facilitate exchange of information between parties within a specific domain [CEN ENV 1613:1994]. A conceptual model is explicitly chosen to be may be informed by, but independent of design or implementation concerns.

Concept: an abstract or generic idea generalized from particular instances [Merriam-Webster].

The TC P&P are [here](http://docs.opengeospatial.org/pol/05-020r25/05-020r25.html). They don't appear to have been updated.

**Comment by cmheazel** [comment]
The spec makes free use of the terms "data model" and "data structure". An easy solution would be to replace all instances of "data" with "conceptual" or "concept". This would also make the spec impalpable to implementors. I would like to position CityGML as a conceptual data model. That is, a conceptual model of a data model. That would allow us to speak to the users in data modeling terms while maintaining the distinction between concept and implementation.

**Comment by 3DXScape** [comment]
Will edit to use only conceptual model and implementation specification uniformly throughout. Editing work for Chuck. Agrred w/o objection today at editors meeting.

**Comment by 3DXScape** [comment]
CH will complete. Agreed to close when completed by CH at 20 August 2020 SWG meeting.

**Comment by cmheazel** [comment]
All instances of `data model` have been converted to `conceptual model` or just `model` depending on the context.
The following instances of `data model` are in the UML model and will have to be changed there; AbstractCityObject, AbstractFeature, Core (package), CityModelMember (featureMember), and Generics (package).

**Comment by TatjanaKutzner** [comment]
I just updated the UML model. I changed `data model` to `conceptual model` in the instances mentioned above.

**Comment by 3DXScape** [comment]
Agreed by unanimous consent, closed 3 Sept meeting

**Comment by cmheazel** [comment]
Found a few additional "data model" instances. Will re-close once I have fixed them.

**Comment by cmheazel** [comment]
Fixed.
