### ISSUE TITLE
The conceptual model of "ADEOf..." datatypes.

### ISSUE THREAD

**Issue by Chika96** [opengeospatial/CityGML-3.0CM#126]
The datatype classes named "ADEOf..." only appear as an attribute type and their structure are not clear in the conceptual model.
There might be relationships between "Any" in ISO19103 and these classes, because they are implemented as "xs:anyType" in GML encoding.

**Comment by TatjanaKutzner** [comment]
Can you give an example where in the GML encoding you discovered "xs:anyType"? When I check the XML schemata it seems encoded correctly, i.e. each ADE property is of type "ADEOfFeatureTypeNamePropertyType".
For instance: 
`<element maxOccurs="unbounded" minOccurs="0" name="adeOfWaterBody" type="wtr:ADEOfWaterBodyPropertyType">`

**Comment by Chika96** [comment]
In figure 31, the class WaterBody has an attribute named adeOfWaterBody.
The data type of this attribute is ADEOfWaterBody.
However the structure of ADEOfWaterBody is not clear because there is no UML diagram for this class. Only its name is shown in Fig.31.
If ADEOfWaterBody can be used as any types, there might be a relationship with “Any” in ISO19103.
![image](https://user-images.githubusercontent.com/58001589/86262119-6fcac800-bbfa-11ea-84ed-72cabcf3155c.png)
Or how about adding a new stereotype "HookDataType" in 6.2 and applying it to this kind of class which should act as a hook? Because it seems to be a special datatype.

**Comment by TatjanaKutzner** [comment]
The ADE data types are also defined in the UML model, however, the UML diagrams for these data types are currently not provided in the specification, see issue #134.
You can find the UML model with the data types here: https://github.com/opengeospatial/CityGML-3.0CM/tree/master/Conceptual%20Model

**Comment by TatjanaKutzner** [comment]
See issue #134 for proposed resolution.

**Comment by 3DXScape** [comment]
Agreed by unanimous consent, closed 3 Sept meeting
