### ISSUE TITLE
Constraints in implementation specifications

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/CityGML-3.0CM#127]
How about normative statements regarding constraints and their implementation in implementation specifications? All the requirements with an identifier like /req/xyz/classes contain the following:

|  Req x | /req/xyz/classes |
| --- | --- |
|  |  For each UML class defined or referenced in the xyz Package: |
| A | The Implementation Specification SHALL contain an element which represents the same concept as that defined for the UML class. |
| B | The Implementation Specification SHALL represent associations with the same source, target, direction, roles, and cardinalities as those of the UML class. |
| C | The implementation Specification SHALL represent the attributes of the UML class including the name, definition, type, and cardinality. |
| D | The implementation Specification SHALL represent the attributes of all parent classes of the the UML class including the name, definition, type, and cardinality. |

Shouldn't there be a statement regarding constraints to? Would a requirement be too strong? For GML, Schematron can be used, for a database encoding, a database constraint, how about e.g. JSON?

**Comment by TatjanaKutzner** [comment]
Thomas and I discussed the issue and we agree that there should be a statement regarding constraints. However, we propose that the statement rather states that the Implementation Specification shall specify how the constraints are represented and not that they are to be represented.
This gives the implementation specifications more flexibility, in particular, when an encoding does not allow the mapping of constraints. In this case the implementation specification can specify that constraints are not mapped.

**Comment by 3DXScape** [comment]
Add new E "The Implementation Specification shall specify how it observes the constraints." Chuck will take care of it.

**Comment by cmheazel** [comment]
New Part F: "The Implementation Specification shall specify how it observes all constraints the Conceptual Model imposes on the UML class."

**Comment by 3DXScape** [comment]
Agreed by unanimous consent, closed 3 Sept meeting
