### ISSUE TITLE
Multiplicity vs cardinality

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/CityGML-3.0CM#129]
In the data dictionary, the term "multiplicity" is used, whereas the term "cardinality" is used in the requirements. Preferably, the same term should be used throughout the whole document, and as the modeling language is UML, that should be "multiplicity". If desired, a reference to https://martinfowler.com/bliki/MultiplicityNotCardinality.html could be added.

**Comment by cmheazel** [comment]
@heidivanparys The requirement and ATS templates have been updated to use `multiplicity` rather than `cardinality`.

**Comment by 3DXScape** [comment]
Agreed for Chuck to close at 20 August 2020 SWG meeting after Chuck has updated the requirements and ATS.

**Comment by 3DXScape** [comment]
Agreed by unanimous consent, closed 3 Sept meeting
