### ISSUE TITLE
Use of term topologic

### ISSUE THREAD

**Issue by gioagu** [opengeospatial/CityGML-3.0CM#132]
I wonder whether you should use the term topologicAL instead of topologic. Both terms exist in English, but it seems that the one with the "al" suffix is used more frequently.

I mean here for example the "TopologicRelationTypeValue"

Maybe a native speaker can help?

Best regards,

GA

**Comment by 3DXScape** [comment]
Topological

**Comment by cmheazel** [comment]
This requires a change to the name of the TopologicRelationTypeValue Class. The term "topological" is used in all other cases with the exception of 7.2.3. In that case the term "topologic" is appropriate since it is used in conjunction with the terms "geometric" and "semantic".

**Comment by TatjanaKutzner** [comment]
Class name and definition have been changed to "Topological" in the UML model.

**Comment by PeterParslow** [comment]
Good call (sorry to be late). "Topologic" is a very rare term. I'd never seen it & had to Google itl it doesn't occur in the web accessible versions of standard dictionaries.

**Comment by 3DXScape** [comment]
Agreed by unanimous consent, closed 3 Sept meeting
