### ISSUE TITLE
Modeling vs Modelling

### ISSUE THREAD

**Issue by benediktschwab** [opengeospatial/CityGML-3.0CM#133]
The word modelling is sometimes spelled according to American English (modeling) and sometimes spelled with two l which is preferred outside the US.

I guess that it should be consistent?

Best regards
Benedikt

**Comment by cmheazel** [comment]
Will update to use non-US specific spelling.

**Comment by cmheazel** [comment]
All instances of "modeling" have been changed to "modelling" except when used as part of a resource title (ex. Unified Modeling Language).

Recommend to close.
