### ISSUE TITLE
UML diagrams of code list classes and ADE data types

### ISSUE THREAD

**Issue by TatjanaKutzner** [opengeospatial/CityGML-3.0CM#134]
The specification does not contain UML diagrams of the various code list classes and ADE data types defined in the UML model for each module. Should they be added as well?
Refers to issue #126, the structure might then become clearer.

**Comment by 3DXScape** [comment]
Either diagrams or additional text might make it clearer. At some level, maybe we should either include all of the UML diagrams or make it clear that only some of the UML is displayed and the full UML model itself is part of the specification and accessible.

**Comment by cmheazel** [comment]
Code lists have neither associations nor attributes. So you will get a diagram of empty boxes. Not very useful. 
We are currently at 298 pages. I suggest we be very selective about what additional information / diagrams we include. When it comes to Standards, more is often not better.
We state in the Standard that the UML model is normative. Issue #138 addresses the need to make it publicly accessible as an OGC normative resource.

**Comment by TatjanaKutzner** [comment]
We could perhaps add code list and ADE data type classes for one module only, so that the reader will at least have an idea about how they are modelled, and then refer to the UML model for the other modules.

**Comment by 3DXScape** [comment]
Chuck will try to follow Tatjana's proposal. Add a figure at beginning of section 10.  City Furniture as example. Tatjana will add new diagram and Chuck will use it.

**Comment by TatjanaKutzner** [comment]
A figure that shows the CityFurniture UML diagram together with the code list and ADE data type classes has been added to the UML model.

**Comment by cmheazel** [comment]
Code list and ADE figures have been included in the standard for all packages where they are provided in the UML model. Figures are extracted from the September 1, 2020 version of the UML model.

**Comment by 3DXScape** [comment]
Noted that this adds a significant bulk but is OK. Choice made to close but realise that may require editing to satisfy comments from external review. Agreed by unanimous consent, closed 3 Sept meeting
