### ISSUE TITLE
Missing sections in chapter 9 + differences in section headers between chapters 8, 9, and Annex A

### ISSUE THREAD

**Issue by TatjanaKutzner** [opengeospatial/CityGML-3.0CM#135]
- Chapter 9 is missing sections on "PointCloud" and "WaterBody".
- Chapter 8.10 is called "Digital Terrain Model", whereas Chapter 9.9 is called "Relief". The same name should be used everywhere.
- Chapter 8 writes module names consisting of several words with spaces inbetween, whereas in Chapter 9 (and also in Annex E) the module names are written without spaces. This should be harmonized.
- Section "A.5 Core" should be placed before "A.2. Appearance" so that there is the same section order as in chapters 8 and 9.

**Comment by 3DXScape** [comment]
I would prefer "Terrain Model". Relief is a term with more limited scope than my idea of the underlying concept. Digital Terrain Model has (for me, anyway) connotation of a specific type of terrain model.

**Comment by TatjanaKutzner** [comment]
I discussed with Thomas, we would prefer "Relief". The term "Digital Terrain Model" seems to be overloaded. Different users understand different things by DTM. According to Thomas the term "Relief" was used as module name in CityGML 2.0, as it has a less limited scope. The term "Relief" also allows to represent Digital Surface Models.

**Comment by cmheazel** [comment]
Section 9 has been fixed.
Section 8.10 has been renamed.
A.5 has been moved as recommended.

**Comment by 3DXScape** [comment]
Agreed to close at 20 August 2020 SWG meeting.
