### ISSUE TITLE
Further Typographical and Grammatical Issues

### ISSUE THREAD

**Issue by TatjanaKutzner** [opengeospatial/CityGML-3.0CM#136]
In addition to issue #118 the following points should be resolved as well:

p. 6 / p. 9
- [x] spatial-temporal -> spatio-temporal (I think that's more commonly used)

p. 9
- [x] Why is "city furniture" written with quotation marks?
- [x] differenti-ations -> differentiations

p. 10
- [x] additonal -> additional
- [x] expension -> extension
- [x] an full extension model -> a full extension model

p. 11
- [x] LoDs. including -> LoDs, including

p. 12
- [x] implementating -> implementation or implementing
- [x] responsiblity -> responsibility
- [x] discrepency -> discrepancy

p. 14
- [x] to conform to this Best Practice -> to this specification

p. 19
- [x] collections -> collection
- [x] inline -> inline in ?

p. 24
- [x] core module -> Core module (occurs several times)
- [x] and linking them with -> and to link them with ?

p. 25
- [x] real world object -> real-world object (occurs several times)

p. 26
- [x] general type of city object -> general type of a city object ?
- [x] main, i.e. the top-level feature types -> main, i.e. the top-level, feature types
- [x] user defined aggregations -> user-defined aggregations
- [x] between features instances -> between feature instances

p. 28
- [x] referenced both by -> referenced both, by
- [x] 7.3.2. Prototypic objects / scene graph concepts -> 7.3.2. Prototypic Objects / Scene Graph Concepts

p. 32
- [x] in different LOD simultaneously -> in different LODs simultaneously

p. 33
- [x] Caption of Figure 7: real world building in the levels of detail 0-3 -> real-world building in the Levels of Detail 0-3

p. 35
- [x] This is particularly the case if terrains [...], if the terrain [...], or if they [...] -> This is particularly the case when terrains [...], when the terrain [...], or when they [...] 
- [x] for all LOD -> for all LODs

p. 37
- [x] to manage dynamic, i.e. time-dependent properties -> to manage dynamic, i.e. time-dependent, properties
- [x] higher frequent or dynamic variations -> higher-frequent or dynamic variations
- [x] time series data -> time-series data or timeseries data (occurs several times, should be harmonized throughout the document)

p. 41
- [x] technology agnostic concepts -> technology-agnostic concepts
- [x] technology specific Implementation Specifications -> technology-specific Implementation Specifications

p. 42
- [x] may be inappropriate for the the application domain -> may be inappropriate for the application domain
- [x] Implemenation Specification -> Implementation Specification

p. 48
- [x] real world objects -> real-world objects (occurs several times)

p. 109
- [x] [cf. ISO 19109] -> should be linked

p. 118
- [x] wich -> which (occurs twice)

p. 133
- [x] Specifies an URI -> Specifies a URI

p. 135 / p. 137
- [x] p <= 1 in the constraints is not formatted correctly (an Asciidoc issue?)

p. 142
- [x] Indicates that city object -> Indicates that the city object

p. 145
- [x] acompanying -> accompanying
- [x] 2D Point Geometry -> 2D Point geometry
- [x] prefered -> preferred

p. 153 / p. 246
- [x] The word "none" is embedded in a grey box. The box should be removed.

p. 161
- [x] comma separated values -> comma-separated values

p. 257
- [x] The definition is provided in bold font and there is a thick line between the rows "Subclass of" and "Stereotype" -> Both should be corrected

p. 278
- [x] implementating technologies -> implementation or implementing

Chapter 9
- [x] StereoType -> Stereotype (occurs in all tables)
- [x] Subclass Of -> Subclass of (occurs in all tables)

Tables 9.1.1. - 9.1.11
- [x] The data types of the attributes are hyperlinks, but the links don't go anywhere
- [x] The superclasses are hyperlinks, but they also don't go anywhere
- [x] What is the purpose of the thick horizontal lines inside the tables? E.g. In table 9.1.2 there is a thick horizontal line between the two role names. (This line occurs in many tables in chapter 9).

Starting from Section 9.2
- [x] All attributes and role names in all tables mention the stereotype &#171;Property&#187;. However, to save space, we decided some time ago (and already did so in a previous version of the document) to remove the stereotype from every attribute. Instead, at the bottom of each table we listed the following sentence "Note: Unless otherwise specified, all attributes and role names have the stereotype «Property»". The stereotypes are there again, the sentence is as well. The stereotypes should be removed again. Only the stereotype &#171;Version&#187; should be listed explicitly with the few attributes where it occurs.
- [x] In addition, the sentence speaks of "rolls" this should be corrected to "role names".
- [x] Attributes with data types from other ISO standards (CharacterString, Character, Integer, DateTime, ID, URI, Real, Boolean, ScopedName, GenericName, TM_Position, TM_Duration, Date, Length, Measure) are linked, but the links don't go anywhere.

All Enumeration tables in Chapter 9 (e.g. p. 141)
- [x] [enumeration] -> &#171;Enumeration&#187;
- [x] The tables have the column names "Literal Values" and "Definitions". This should be changed to "Literal value" and "Definition", as all other tables also have the column names in singular.

General points
- [x] Mix of British and American English throughout the specification (e.g. color / colour; z / s e.g. in generaliz/sation)
- [x] All tables should have text-width, in particular the tables for requirements classes and requirements seem to be shorter.

**Comment by cmheazel** [comment]
Status August 7, 2020 - fixed issues up through page 48.

**Comment by TatjanaKutzner** [comment]
The following sub-issues have been implemented in the UML model:
p. 118, p. 133, p. 142, p. 145, and p. 161

The other sub-issues do not require updates to the UML model.

**Comment by cmheazel** [comment]
p. 109 - this reference to ISO 19109 is in a definition exported from the UML model.  We make it a point not to modify exported content except when absolutely necessary.  Since the section header for this class does include a link to the ISO 19109 citation, an additional link is not essential.
Chapter 9 - Corrected the templates for Enumerations, Subclass of, and Stereotypes.

**Comment by cmheazel** [comment]
Notes for the final draft:
Section 9.2 - the EA template allows me to include or omit stereotypes.  It does not allow me to filter on stereotype value.  I will attempt come up with a tool to strip the Property stereotypes out without corrupting other content. Otherwise this will be a manual editing task.
9.1.1-9.1.11 + 9.2 - the links are generated by the EA templates. Cleanup for the final draft will include testing every link and removing those which do not have a valid target.
P 257, 9.1.1-11 - The thick lines appear to be an artifact of the rendering process. They are not in the AsciiDoc source. Will work with OGC staff to locate and remedy the problem.
General: review the final draft and make sure the use of language is consistent. We previously agreed to use British English.

**Comment by cmheazel** [comment]
P135-137, P153 / 246, P257 - these appear to be errors in the manual editing and will be cleaned up in the final draft.

**Comment by TatjanaKutzner** [comment]
@cmheazel 
Re "Starting from Section 9.2": Not sure, if you are still working on that task, but chapter 9.1 now contains "rolls" and starting with 9.2 many places in the document contain now "roll names".

**Comment by cmheazel** [comment]
@TatjanaKutzner I just checked the AsciiDoc on GitHub and all I found was "roll name". 
However, the term "rolls" was used in the dictionary notes on the three ISO classes I added. They have been fixed.

**Comment by cmheazel** [comment]
Section 9.2 - I now have a shell script which strips out the stereotype<<Property>>.
Have added entries in the glossary for all ISO concepts which are not included in the data dictionary. This will enable the links in the ISO data dictionaries which currently do not go anywhere. I'll continue this approach for the rest of the data dictionaries.
Note: definitions are needed to go with the terms.

**Comment by TatjanaKutzner** [comment]
@cmheazel It should be "role name", not "roll name".

**Comment by cmheazel** [comment]
@TatjanaKutzner Yup. I've fixed it in the AsciiDoc. Just need to fix the UML template.

**Comment by cmheazel** [comment]
Done
