### ISSUE TITLE
Further Substantive Editorial Issues

### ISSUE THREAD

**Issue by TatjanaKutzner** [opengeospatial/CityGML-3.0CM#137]
In addition to issue #119 the following points should be resolved as well:

p. 11
- [x] Transportation facilities (both graph structures and 3D surface data) -> Also 3D space data is represented, not only graph structures and 3D surface data

p. 20 (Classes painted in blue)
- [x] their class names carry the name of the Requirements Class as prefix -> the class names are actually preceded by the package name, it's not just a prefix.

p. 24
- [x] These are grouped within the Construction module. -> Gives the impression that Building, Bridge, and Tunnel are submodules defined within the Construction module.

p. 139
- [x] The tables have the column name "Member name". The columns should be named "Attribute", as is the case with all other tables
- [x] The tables have the column name "Type". The columns should be named "Type and Multiplicity", as is the case with all other tables. Even if the multiplicity is not shown, since it is implicitly 1.

p. 167
- [x] Except for the attributes `boolValue` and `intValue` all other attributes do not abbreviate the value type they represent ->Thus, to be consistent, would it make sense to write out these values types as well in the attributes names, i.e. `booleanValue` and `integerValue` ?

p. 169
- [x] Similarly here: only the type `bool` is abbreviated -> To be consistent, would it also make sense here to write `boolean` instead?

p. 220
- [x] The tables for AbstractFillingElement and AbstractFillingSurface provide columns for role names, but they do not contain values -> The columns should be removed.
- [x] AbstractFillingElement is the abstract superclass for different kinds of elements that fill the openings of constructive elements.
-> Is this correct? Are filling elements only used for constructive elements (i.e. elements that are subclass of AbstractConstructiveElement) or for constructions in general? If yes, then Windows and Doors would only be allowed for constructive elements.

p. 188 / p. 218 / p. 219 / p. 221 / p. 222 / p. 227 / p. 241 / p. 253 / p. 254 / p. 263
- [x] The role name "boundary" does not have a definition. The associations are provided in the UML diagrams for illustration purposes only, since the associations are inherited. However, we discussed in a recent meeting that it is difficult to omit the role names when generating the tables automatically from the EAP project and decided to add manually some information to the role names that they are inherited from the association between `AbstractSpace` and `AbstractSpaceBoundary`.

p. 272
- [x] Does the prefix `core` of `core:AbstractCityObject` refer to the Core package on the UML level? If yes, then it might be better to write `Core::AbstractCityObject`. Currently the prefix resembles the namespace prefix used on the XML level, which might be a bit confusing, as the specification is platform-independent.

p. 274
- [x] To highlight the differences between CityGML 2.0 it might be better to change the following texts:
a feasible solution is to derive -> a feasible solution in CityGML 2.0 was to derive
For this reason, CityGML provides -> For this reason, CityGML 3.0 provides

p. 283
- [x] It's unclear what the meaning of this text is:
"This object or attribute does not duplicate one that has already been defined by the Conceptual Model, . That the other extension methods provided by the CityGML Conceptual Model do not provide a more specific representation."

Chapter 9
- [x] For some attributes in various tables no multiplicity is shown. Is it clear to every reader, that these attributes have by default the multiplicity 1?

Tables 9.1.1. - 9.1.11
- [x] FeatureType [] -> What multiplicity does [] represent? (Empty brackets occur also on the following pages)
- [x] Some role name fields are empty, although a data type is provided for them

**Comment by TatjanaKutzner** [comment]
Re p. 188ff: Thomas and I propose to add the information on inheritance directly to the UML model, then we do not have to add it manually to the specification and it doesn't get lost, in case the specification content is created later again from the UML model.

**Comment by cmheazel** [comment]
Page 139 - the tables in question are for Unions. These represent choice functions - the object can be one and only one of these alternatives. The "attributes" of a union are the members of the set of alternatives. Thus, they are members, not attributes. The same is true of multiplicity. The choice is always one and only one so a "multiplicity" field is both redundant and misleading.

**Comment by cmheazel** [comment]
Page 283 - this is primarily a formatting issue. The two sub-tests have been broken out into separate rows in the table. Their purpose is to validate uniqueness and the use of an appropriate extension mechanism. The update should be a bit clearer on this point.

**Comment by cmheazel** [comment]
Chapter 9 - The multiplicity values are extracted from the UML model. Since a multiplicity of 1 is the UML default, the multiplicity field is not populated in those cases. Therefore, the multiplicity must be entered manually. I may have missed a couple.

**Comment by TatjanaKutzner** [comment]
The following sub-issues have been implemented in the UML model:
p. 188 / p. 218 / p. 219 / p. 221 / p. 222 / p. 227 / p. 241 / p. 253 / p. 254 / p. 263: Definitions have been added to each role name "boundary" in the UML model.

The other sub-issues do not require updates to the UML model.

**Comment by cmheazel** [comment]
p.167 : In the September 1, 2020 version of the UML model the boolValue and intValue attributes of TimeValuePair have not been updated as requested by this issue. Please resolve one way or the other.
Note: changing the names of these attributes will also impact constraints on GenericTimeseries and TimeValuePair.

**Comment by cmheazel** [comment]
p. 167 : The 'bool' value from the enumeration TimeseriesTypeValue have not been updated as requested by this issue. Please resolve one way or the other.

**Comment by cmheazel** [comment]
p.220 : Please confirm that the definition for AbstractFillingElement is correct.

**Comment by TatjanaKutzner** [comment]
p. 220: The definition is too restrictive and should be changed to: 
"AbstractFillingElement is the abstract superclass for different kinds of elements that fill the openings of a construction." 

In this way, filling elements can fill openings of constructions in general. 
And the definition is also consistent with the definitions of AbstractFurniture and AbstractInstallation.

I will change that in the UML model.

**Comment by TatjanaKutzner** [comment]
p. 167:
I discussed this with Thomas: We should stick to "bool" and "int". These abbreviations are commonly known to practicioners (e.g. from programming languages), are used consistently in the data model, and we should not make the names unnecessarily longer (which would also mean longer names in the GML encoding).

However, to be consistent, the "integer" value from the enumeration TimeseriesTypeValue needs to be changed to "int".
I will change that in the UML model and also adapt the constraint of GenericTimeseries.

**Comment by 3DXScape** [comment]
Are we ready to close? Are we just waiting to see these in the PDF? Am I missing something?

**Comment by cmheazel** [comment]
@3DXScape 
P 220 and Sections 9.1.1-1.11 have to do with the manual editing after the tables have been exported from the UML model. Since I have not yet re-exported the tables from the current model this issue should be left open.

**Comment by cmheazel** [comment]
P220 AbstractFillingShape and AbstractFillingSurface no longer have associations.
9.1.1 - 9.1.11 - all CityGML roles have names and types. 
Not all ISO roles have names. This content is exported from the TC211 Harmonized UML model. Content is missing in the standard because it is missing in the ISO model. Since we do not control the ISO model we cannot populate these fields.

**Comment by TatjanaKutzner** [comment]
All points have been resolved, thus, the issue will be closed.
