### ISSUE TITLE
Further Conceptual Issues

### ISSUE THREAD

**Issue by TatjanaKutzner** [opengeospatial/CityGML-3.0CM#139]
In addition to issue #117 the following points should be resolved as well:

p. 11
- [x] Does the categorisation of LODs into regional, city, city district and architectural models still apply? Do floorplans, which can now be expressed in LOD0, represent a regional level of detail?

p. 274
- [x] "However, following the CityGML conceptual model, constraints should at least be expressed on ADE subclasses of core:AbstractSpace to limit the types of space boundaries (i.e., instances of core:AbstractSpaceBoundary) that may be used to model the boundary of a space object."
-> The CityGML conceptual model currently does not include such constraints.

**Comment by clausnagel** [comment]
Re 2: I think the corresponding constraints are missing in the current draft and must be added. It must be clear which subclasses of AbstractSpaceBoundary may be used (and not used) in the „boundary“ association of a specific space class. I remember from the modeling subgroup that OCL cannot be used for expressing the constraints because this might exclude a priori unknown ADE classes. I think the agreement was to add them as plain text (conformance requirement, ...)? An ADE should provide similar constraints.

**Comment by TatjanaKutzner** [comment]
Re 1:
Thomas and I discussed that the categorisation is not correct any more. We propose to use the following categorisation:
LOD0 - Highly generalised model
LOD1 - Block model / extrusion objects
LOD2 - Realistic, but still generalised model
LOD3 - Highly detailed model

Re 2:
Yes, there was an agreement in the modeling subgroup to add the constraints as plain text, not as OCL. 
The constraints were already defined by the modeling subgroup some months ago in this spreadsheet:
https://docs.google.com/spreadsheets/d/1UtWiH7qVXClpq_rFHMM5P_zLmp5e-li1_ECi1amK1p4/edit?usp=sharing 
The proposed resolution would be to add these constraints as requirement in tabular form to each module in the specification.
A requirement should also be added to the ADE chapter, that ADEs should provide constraints on space boundaries.

**Comment by cmheazel** [comment]
@TatjanaKutzner As I understand this resolution:
1) A new requirement will be created for each class that is listed in the Spreadsheet (columns A). That requirement will capture the spatial constraints which apply to that class.
2) This resolution will not result in any changes to the UML model (no OCL?).
3) A "generic" requirement will be created for ADEs stating that space boundary constraints shall be identified.

Now: how can we write "possible classes from ADEs" as a testable requirement?

**Comment by 3DXScape** [comment]
Need to review PDF to confirm that this is included as expected.

**Comment by cmheazel** [comment]
Action: CH to write a requirement for each package which will specify that the spatial boundary constraints documented in table xyz are normative.

**Comment by 3DXScape** [comment]
Table is now included but still need to express these constraints as a requirement for each class, referencing table.

**Comment by cmheazel** [comment]
A requirement making the spatial boundary constraints normative has been added to Bridge, Building Model, City Furniture, City Object Group, Construction, Core, Generics, Transportation, Tunnel, Vegetation, and Water Body Modules. 

With these changes, I recommend that this issue should be closed.

**Comment by 3DXScape** [comment]
Agreed by unanimous consent, closed 3 Sept meeting
