### ISSUE TITLE
point cloud

### ISSUE THREAD

**Issue by volkercoors** [opengeospatial/CityGML-3.0CM#14]
PointCloud is definitely not a Feature. It is a geometrical representation of spatial entities / city objects. The Point Cloud should not be modelled as FeatureType, but as a Geometry. And maybe not as part of the core.

![grafik](https://user-images.githubusercontent.com/5288711/45267178-d8661500-b467-11e8-97c1-b51097f11086.png)

**Comment by TatjanaKutzner** [comment]
Based on discussions between Volker and Thomas at the last OGC meeting on whether the PointCloud class should be part of the Core module or not, I modified the UML model now in such a way that the PointCloud class becomes part of an individual PointCloud module.
![grafik](https://user-images.githubusercontent.com/5949401/47028017-c8c5a480-d168-11e8-80fa-2dd9fcf28beb.png)
commit https://github.com/opengeospatial/CityGML-3.0CM/commit/8e2715cdc123418aafa08515618c734188c8c132

**Comment by TatjanaKutzner** [comment]
In general, I think it is fine to move the class to an individual module. 

However, one disadvantage of this representation is that a geometry class needs to be provided again within a thematic class. CityGML 3.0 aims at bundling all geometry classes as far as possible in the Core module, the classes in the thematic modules inheriting the geometries by extending them from the abstract classes in the Core module.

**Comment by TatjanaKutzner** [comment]
The new PointCloud module introduces a module dependency from the Relief module to the PointCloud module, as the Relief module requires the point cloud concept to represent the mass point relief. We will need a requirement that when the Relief module is used, also the PointCloud module needs to be included.

**Comment by clausnagel** [comment]
+1 for moving _PointCloud_ to an optional module. Not sure though why we need a point cloud to model the mass points of a terrain. Does not sound like a natural choice to me. Why not simply use _GM_MultiPoint_ for _MassPointRelief_ like in CityGML 2.0?

**Comment by 3DXScape** [comment]
Does anyone see the need for or anything in what we have done so far that would make it difficult/impossible to use some other geometric representation (e.g. CSG or simplicial complexes) in CityGML 3.0. Is mixing and matching possible?

**Comment by clausnagel** [comment]
Resolved in draft release [3.0.0-draft.2018.12.17.1](https://github.com/opengeospatial/CityGML-3.0CM/releases/tag/3.0.0-draft.2018.12.17.1)
