### ISSUE TITLE
Modular Specification

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/CityGML-3.0CM#145]
The OAB has directed the following:

    Normative terms particular to the spec up are listed in the front of the document
        Collection, Web API
    Other terms in a glossary for terms in an annex 
        Conformance class, requirements class
    With links internal and external to source spec.

CityGML 3.0 should be updated to comply with this direction.

**Comment by cmheazel** [comment]
1) A glossary annex has been added to the CityGML 3.0 standard
2) Terms and definitions which are not specific to CityGML have been moved to the glossary
3) Acronyms which are not specific to CityGML have been moved to the glossary

**Comment by 3DXScape** [comment]
Discussed and agreed to close by editors
