### ISSUE TITLE
Undefined ISO Classes

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/CityGML-3.0CM#147]
CV_DiscreteGridPointCoverage, GM_MultiCurve, and GM_MultiSurface are not defined in the TC-211 Harmonized UML model. As a result, these classes are not defined in the CityGML Standard. Locate authoritative definitions and update the data dictionary.

**Comment by 3DXScape** [comment]
Seems like we need at least CV_DiscreteGridPointCoverage and GM_MultiSurface.

**Comment by cmheazel** [comment]
Peter will provide the definitions for CV_DiscreteGridPointCoverage, GM_MultiCurve, and GM_MultiSurface - CH will enter them into the table.
Agreed to close after the definitions have been entered. 20 August 2020 SWG meeting.

**Comment by PeterParslow** [comment]
Here is some text copied from ISO 19107:2005, which has a "semantics" subclause for each of its classes:

GM_MultiCurve is an aggregate class containing only instances of GM_OrientableCurve. The association role “element” shall be the set of GM_OrientableCurves contained in this GM_MultiCurve.

GM_MultiSurface is an aggregate class containing only instances of GM_OrientableSurface. The association role “element” shall be the set of GM_OrientableSurfaces contained in this GM_MultiSurface.

It is a little more awkward in ISO 19123:2007:

**discrete coverage** is defined as "coverage that returns the same feature attribute values for every direct position within any single spatial object, temporal object or spatiotemporal object in its domain"

CV_DiscreteGridPointCoverage is described with "The domain of a CV_DiscreteGridPointCoverage (Figure 7) is a set of CV_GridPoints (8.5) that are associated with records of feature attribute values through a CV_GridValuesMatrix (8.14)."

So we could go with a definition like:

"coverage that returns a GridPoint for every direct position within any single spatial object, temporal object or spatiotemporal object in its domain" - but that sounds rather circular to me....

**Comment by cmheazel** [comment]
Here are the definitions I went with.
GM_MultiCurve: An aggregate class containing only instances of GM_OrientableCurve. The association role “element” shall be the set of GM_OrientableCurves contained in this GM_MultiCurve.
GM_MultiSurface: An aggregate class containing only instances of GM_OrientableSurface. The association role “element” shall be the set of GM_OrientableSurfaces contained in this GM_MultiSurface.
CV_DiscreteGridPointCoverage: A coverage that returns the same feature attribute values for every direct position within any single spatial object, temporal object or spatiotemporal object in its domain

**Comment by 3DXScape** [comment]
Agreed by unanimous consent, closed 3 Sept meeting

**Comment by cmheazel** [comment]
Also need definitions for:
GM_MultiPoint (19107)
TM_Position (19108)

**Comment by PeterParslow** [comment]
From the "committee member copies" I've acquired over the years: 

19107:2003 gives the semantics of GM_MultiPoint as 

"GM_MultiPoint is an aggregate class containing only points. The association role “element” shall be the set of
GM_Points contained in this GM_MultiPoint."

(19107:2019 doesn't contain this class)

From a late draft of 19108:2002:

"TM_Position is a union class that consists of one of the data types listed as its attributes. Date, Time, and
DateTime are basic data types defined in ISO/TS 19103."

Note, although not modelled this way, it is the implementation class for the specialisation of TM_TemporalPosition when the temporal reference system is constrained to Gregorian Calendar. It is only a little wider than the more commonly used ISO 19103::DateTime type (in that TM_Position has the rather odd union choice "anyOther: TM_TemporalPosition", at least in my 'text for FDIS'). Note also that the UML model in the harmonised model doesn't seem to match my draft of the standard. This could be "2002 quality control" or it could be that the published standard differs from the "text for FDIS" that I have.

**Comment by cmheazel** [comment]
@PeterParslow Thanks. Changes applied. Closing again.
