### ISSUE TITLE
Abstract Logical space

### ISSUE THREAD

**Issue by volkercoors** [opengeospatial/CityGML-3.0CM#15]
Just as a reminder:

a good example to model logical space (in CityGML 2.0) in 3D cadastre has been publish and further developed since than by Ms Gozdz (without teh need of an Abstract Logical Space class/interface):

Gozdz, K., Pachelski, W., van Oosterom, P., and Coors, V.: The possibilities of using CityGML for 3D representation of buildings in the cadastre, In: van Oosterom, P. & Fendel, E. (Eds.): Proceedings 4th International Workshop on 3D Cadastres, 9-11 November 2014,Dubai,United Arab. Emirates, ISBN 978-87-92853-28-8, pp 339-361

https://www.coors-online.de/wp-content/uploads/2014/11/paper-3D-cadastre-gozdz.pdf
https://www.coors-online.de/wp-content/uploads/2014/11/presentation-3D-cadastre-Coors.pdf

![grafik](https://user-images.githubusercontent.com/5288711/45267208-7c4fc080-b468-11e8-9aac-8757f48018a1.png)

**Comment by volkercoors** [comment]
https://www.fig.net/resources/publications/figpub/FIG_3DCad/FIG_3DCad-final.pdf
the book just summarizes the 2014 paper, a newer reference, but no new content.
see summary in chapter 5.2

**Comment by TatjanaKutzner** [comment]
In the web conference on 18 April 2019 we discussed that we will check the paper and use it as example for logical spaces.
