### ISSUE TITLE
Pending Editorial Changes

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/CityGML-3.0CM#154]
Editorial changes planned or in-work

**Comment by cmheazel** [comment]
- [x]  "Allowed Space Boundaries"

1) Reformat all "allowed space boundaries" tables to match the table in Core.
2) Also make sure that the anchor is all lower case and has a leading NL.
3) Table in empty in the Vegetation package. If this is correct, then delete the table and all references. 

Completed 9/18/20

**Comment by cmheazel** [comment]
- [x]  Make sure all links to the Users Guide resolve to http://docs.opengeospatial.org/DRAFTS/20-066.html

**Comment by cmheazel** [comment]
- [ ]  Rotate the following images 90 degrees to make them more readable: 14, 17, 18, 19, 21, 29, 40, 48, 56, 59, 62

**Comment by cmheazel** [comment]
- [x]  Center Figures.

**Comment by cmheazel** [comment]
- [x]  ISO Data Dictionaries - still missing content.

Moved to issue #165

**Comment by cmheazel** [comment]
- [x]  Clean up formatting of OCL constraints

**Comment by cmheazel** [comment]
- [x] Check all internal links, remove those with no target, fix those which are broken. Alternate, add definitions for the undefined targets in the glossary. That way every concept in the model is represented.

Resolution: extended the glossary to include entries for all links which did not have a target. Provided definitions where available.

**Comment by cmheazel** [comment]
- [x]  Update ATS to bring back into alignment with the requirements.
See issue #155

**Comment by cmheazel** [comment]
- [x]  Enumerations for Construction are missing from Data Dictionary

**Comment by TatjanaKutzner** [comment]
- [x] Heading of Chapter 1 is missing

**Comment by TatjanaKutzner** [comment]
- [x] References to bibliography entries are not displayed properly any more. 
Previously they were displayed in the form Kolbe 2009, Biljecki et al. 2015, Kaden & Clemen 2017, etc. Now they have the form [Kolbe2009], [Biljecki2015], [Kaden2017], which should be corrected.

**Comment by cmheazel** [comment]
- [x]  OtherConstruction - move TopLevelFeatureTypes to the top of the Data Dictionary for each Package.
Not implemented. The classes in the data dictionaries are sorted alphabetically. This is appropriate. Sorting by TopLevel vs regular FeatureType is provided in Section 8.

**Comment by TatjanaKutzner** [comment]
- [x] The ISO 19111 Package element in figure 13 has a different color. The color was corrected in commit f8447f7. Please integrate the updated figure.

@TatjanaKutzner Very subtle. I didn't see it in the rendering. I had to compare the EA models. Figure has been updated.
@cmheazel Yes, very subtle. In my EAP file it looks correct. I only noticed it when I looked at the specification that contained the rendered figure.

**Comment by cmheazel** [comment]
- [x]  Address empty rows in Allowed Space Boundaries for Vegetation, Construction, Bridge, Building, Tunnel
Resolved: empty fields now say "No boundaries allowed".

**Comment by cmheazel** [comment]
Proposed changes which have not been addressed are moved to issue #171
