### ISSUE TITLE
Update ATS

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/CityGML-3.0CM#155]
The Abstract Test Suite has not kept up with changes to the requirements.

**Comment by cmheazel** [comment]
ATS now matches the requirements. Will close once the links between requirements and ATS are validated.

**Comment by cmheazel** [comment]
Links have been validated. Broken link between ADE tests and requirements have been fixed.

**Comment by TatjanaKutzner** [comment]
The link /req/generics/use does not work.

**Comment by TatjanaKutzner** [comment]
Proposed changes which have not been addressed are moved to issue #171
