### ISSUE TITLE
ISO 19107

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/CityGML-3.0CM#158]
Some elements of the harmonized model reference ISO 19107:2019 elements rather than 19017:2003. The result is that we have a mixture of 2003 and 2019 elements in the model. 
1) should be cite both the 2003 and 2019 standards as normative references?
2) should we add a short explanation of the issue?

**Comment by TatjanaKutzner** [comment]
Can you give an example, where an element from ISO 19107:2019 is used? Because in the EAP project there is only an ISO 19107:2003 package from which geometries were taken.

**Comment by cmheazel** [comment]
The EAP also includes the 19107 Draft International Standard (which I believe became 19107:2019).  An interesting example is GM_Point. GM_Point is defined in 19107:2003. But it has an association with Point which is defined in the 19107 DIS. Clearly the issue lies with the TC211 Harmonized Model. But the disconnect shows up in our conceptual model. Since someone is bound to notice, do we want to address it now?

BTW: the definition for Point starts "GM_Point (figure 9) is the basic---".

**Comment by TatjanaKutzner** [comment]
I understand now what you mean. That is a very specific issue coming from the TC211 Harmonized Model and which we cannot influence. Thus, I would rather suggest to not address this now.
