### ISSUE TITLE
Comments from Nobu Ishimaru

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/CityGML-3.0CM#160]
- [x] Table of Contents - "11. ISO Concepts" and "12. Abbreviated Terms" [-> should be included in Annex D?]

- [x] iii. Preface - "More content to be provided." [What is the meaning of this sentence?]

- [x] iv. Submitting organizations - [How about moving CityGML logo and introduction of homepages to other part such as vii. Acknowledgements?] NOTE [What is the meaning of this NOTE?] "To be provided" -> should be mentioned

- [x] 2. Scope - "implementable expension mechanism" -> "implementable extension mechanism" [?] "potrayal formats" -> "portrayal formats" "LoD" -> "LOD" [align with 12. Abbreviated Terms]

- [x] 3. Conformance - "1. Conceptual Models" link to "#conceptual_model_definition" -> should linked to "#conceptual-model-definition"

- [x] 4. References - ISO 19123 "geomentry" -> "geometry"

- [x] 7.2.1 - bi-temporal? bitemporal?

- [x] 7.2.2 - "Hierachy" -> "Hierarchy"

- [x] 7.4.4 - "[[Lowner2016]]" link to "#Lowner2016" -> should be "[Lowner2016]" link to "#Löwner2016", 
Figure 8 "[Lowner2016]" link to "#Lowner2016" -> should link to "#Löwner2016" 
[or id in Annex E should be modified as "Lowner2016"?]

- [x] 8.2.1 - "Implemenation Specification" -> "Implementation Specification"

- [x] 8.2.5 - "LoD" -> "LOD" [align with 12. Abbreviated Terms]

- [x] 8.7.3 - "Genericsn" -> "Generics"

- [x] 8.15 - "Contruction module" -> "Construction module"

- [x] 9.1.3 - "Integer" link to "#integer-section" -> should link to "#Integer-section" 
[or id should be modified as "integer-section"?]

- [x] 9.1.13 - "Not-navigable associtation" -> "Not-navigable association"

- [x] 9.1.14 - "ISO 19108:2006" link to "#iso19108" [where is iso19108?]

- [x] 9.2.1. Classes - "GenericName" like to "#GenericName-section" -> should link to "#GenericName-Section" 
[or id should be modified as "GenericName-section"?]

- [x] 9.13.1 - "sucessor" -> "successor"

- [x] 9.17.1 - "accessability" -> "accessibility" [?]

- [x] 10.4 - "corrresponding" -> "corresponding

- [x] 10.5 - "capabilty" -> "capability"

- [x] A.7 - "confilcts" -> "conflicts", 
 "attribue" -> "attribute"

- [x] A.14 - "Unresolved directive in abstract_tests/ATS_WaterBody.adoc - include::WaterBody/ATS_WaterBody_Boundaries.adoc[]" [?] "Unresolved directive in abstract_tests/ATS_WaterBody.adoc - include::WaterBody/ATS_WaterBody_ADE_Use.adoc[]" [?]

- [x] Annex C: Changelog for CityGML 3.0
[will you add changelog before TC voting?]

- [x] 11. ISO Concepts
"[[iso19108]]" should be modified as "[iso19108]" with appropriate link

- [x] In many sections:
"in the figure Figure" -> "in the Figure"
"mutiplicity" -> "multiplicity"
"multiplicies" -> "multiplicity" [?]

- [ ] [I think the font size in the UML figures is too small to read.
Is there any way to make them larger? (e.g. link to large image?)]

**Comment by TatjanaKutzner** [comment]
Annex C: Changelog for CityGML 3.0
I removed this chapter now. We decided some time ago, that we do not list changes between CityGML 2.0 and 3.0 in the specification. The changelog will start with CityGML 3.1.

**Comment by TatjanaKutzner** [comment]
11. ISO Concepts

I added ISO 19108 to Chapter 4. The official standard is ISO 19108:2002. In Figure 13, however, an ISO 19108:2006 package is shown. This is the only package I have in Enterprise Architect. It is a corrigendum to the 2002 version.

Thus, should we rather reference this corrigendum, or is it uncommon to reference corrigendums?

**Comment by cmheazel** [comment]
@TatjanaKutzner Reference the Corrigendum. There is a precedent.  For years we commonly referenced the corrigendum of ISO 19115 in OGC standards.

**Comment by TatjanaKutzner** [comment]
@cmheazel Good to know, I referenced the corrigendum now.

Most typos have been corrected. The remaining ones seem to occur in the templates. @cmheazel Could you please take care of those?

**Comment by TatjanaKutzner** [comment]
iii. Preface: The idea was probably to add more text to this section. I removed the sentence.

iv. Submitting organizations: 
- I moved the OGC logo and links to web pages to vii. Acknowledgements. Also not the best place, but better then before.
- I removed the note that we still have to add an OGC logo. I don't think that the logo is required.

**Comment by cmheazel** [comment]
All issues except for the font size on the UML diagrams have been addressed.

**Comment by cmheazel** [comment]
Proposed changes which have not been addressed have been moved to #171
