### ISSUE TITLE
Terminology

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/CityGML-3.0CM#162]
I'm looking for agreement on a couple terms we use in the specification:

1) CityGML Conceptual Model (all caps) = the name of the UML model
2) CityGML Conceptual Model Standard = the name of the standard including both the document and the UML model
3) CityGML conceptual model = a conceptual model that is part of the CityGML family of standards.

Also, will there ever be a part 2, 3, etc.?  If so then the need to change the name to CityGML 3.0 Part 1: Conceptual Model.

**Comment by TatjanaKutzner** [comment]
Wasn't that part of another issue this afternoon with a bit different content? I already started to type an answer...
I wanted to suggest to reduce it to two concepts:

1. CityGML 3.0 Conceptual Model Standard = a human accessible representation of the Conceptual Model with supporting informative text, requirements, and ATS.
I usually associate a document (PDF, HTML, or paper document) with the term "standard". It might be a bit confusing to call something a standard that consists of different things (document and UML model).

2. CityGML 3.0 Conceptual Model = the UML model. This is the complete, definitive, machine readable, Conceptual Model.

The current document already is referred to as Part 1. I thought that the GML encoding will become Part 2.

**Comment by cmheazel** [comment]
@TatjanaKutzner Sorry, I was afraid this issue would get buried so I broke it out as a separate issue.
So we are setting a pattern ---
A conceptual model standard is a document
A conceptual model is a machine readable model which **may** be described by a conceptual model standard
An implementation specification is a document
A schema (XML, JSON) is a machine readable schema which **may** be described by an Implementation Specification

**Comment by TatjanaKutzner** [comment]
This pattern sounds good to me and I also think it will be understandable very well by the users.

I would not differentiate between upper and lower case, i.e. "Conceptual Model" and "conceptual model". It's a very subtle difference in writing, which might not be noticed by every reader and might also confuse, even if we explain the different meanings.

**Comment by 3DXScape** [comment]
I get the Conceptual Model = the/this CityGML conceptual model, conceptual model = a conceptual model. Tatjana may be correct that this is a subtle difference. But we could take advantage of the fact that we understand it and someone unaware of the difference wouldn't be losing any information and someone aware would be gaining information so it seems like a mildly positive thing to make Chuck's distinctions - and won't harm understanding for the already unaware.
