### ISSUE TITLE
Model Driven Architecture

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/CityGML-3.0CM#163]
I want to introduce Model Driven Architecture to this standard. In particular, the following concepts:
- Platform Independent Model - the conceptual model
- Platform Specific Model - the implementation specifications

I think it would help explain CityGML if we talk about it as an implementation of MDA principles.

Reference https://www.omg.org/cgi-bin/doc?ormsc/14-06-01.

**Comment by TatjanaKutzner** [comment]
I like the idea of introducing MDA explicitly to the standard. Implicitly we already follow the MDA approach.

However, I don't agree with the suggested categorisation. According to MDA it should be the following way:

- Platform Independent Model (PIM): The CityGML UML model independent of any particular platform (in our case independent of GML and other encodings, i.e. without tagged values required for automatic derivation of GML application schemas and other encodings). This is the conceptual model.
- Platform Specific Model (PSM): The same CityGML UML model, but now with aspects of the specific platform (in our case with tagged values required for automatic derivation of GML application schemas and other encodings)
- Platform Model (PM): The encoding of the PSM (in our case the GML xsds and other schemas or code) which is specified in the implementation specifications

This is shown here:
![grafik](https://user-images.githubusercontent.com/5949401/96278187-80e6eb80-0fd5-11eb-83da-4d27402ecae7.png)
Reference: Section 3.1.2 in https://mediatum.ub.tum.de/doc/1280909/1280909.pdf
Section 6.2 in the reference might also be of interest, it discusses the classification of the GML-specific tagged values (referred to as ISO 19136 UML profile) at the PSM level.

**Comment by cmheazel** [comment]
I basically followed this model although I did not use the term Platform Model. I simply referred to schema and other artifacts. An Implementation Specification includes the ISM and PM (schema).
