### ISSUE TITLE
Stereotypical vs. Geotypical

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/CityGML-3.0CM#164]
From Carl's redlines on section 8.4 (City Furniture):  CDB and the CDB community use the term “geotypical”. Also, vendors supporting the Modelling and Simulation community as well as some major GIS vendors use the term “geotypical”. Should CityGML align with the M&S usage?

Comments?

**Comment by TatjanaKutzner** [comment]
I would suggest the term "prototypical". This complies with section 7.3.2 which speaks of prototypical objects / prototypes. This term was also commonly used in CityGML 2.0.

To me the semantics of "geotypical" seems to differ. The term seems to be commonly used in comination with "terrains" and also expresses that these terrains or other objects are not necessary a realistic representation of the real world, whereas CityGML intends to represent objects of the real world in a realistic way.

**Comment by TatjanaKutzner** [comment]
change to "prototypical or geotypical"
-> Consensus of the SWG as of 22 February 2021

**Comment by cmheazel** [comment]
February 24, 2021: Changes have been made and merged.

**Comment by TatjanaKutzner** [comment]
Looks great, thus, the issue can be closed.
