### ISSUE TITLE
Missing ISO Definitions

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/CityGML-3.0CM#165]
We still need definitions for:
CV_DomainObject
CV_GridPointValuePair
CV_ReferenceableGrid
Geometry (ISO 19107)
GM_CompositPoint
GM_MultiPrimitive
IO_IdentifiedObjectBase
TM_Duration (ISO 19108)

**Comment by TatjanaKutzner** [comment]
Here are the definitions from the ISO standards:

**CV_DomainObject**
An element of the domain of the CV_Coverage. It is an aggregation of objects that may include any combination of GM_Objects (ISO 19107:2003), TM_GeometricPrimitives (ISO 10108), or spatial or temporal objects defined in other standards, such as the CV_GridPoint defined in this International Standard.

**CV_GridPointValuePair**
A subtype of CV_GeometryValuePair that has a GM_GridPoint as the value of its geometry attribute.

**CV_ReferenceableGrid**
A subclass of CV_Coverage that relates the grid coordinates to an external coordinate reference system.

**Geometry**
Geometry is the root class of the geometric object taxonomy and supports interfaces common to all geographically referenced geometric objects.
-> Please note: Geometry is defined in ISO 19107:2019. It's the equivalent of GM_Object defined in ISO 19107:2003. In the EA project, a dependency is defined between GM_Object and Geometry. We once discussed in #158 not to include ISO 19107:2019 in our standard and also to ignore these dependencies. Thus, we should simply remove the dependency manually from the specification.

**GM_CompositePoint**
A GM_Complex containing one and only one GM_Point.

**GM_MultiPrimitive**
The root class for all primitive aggregates. The association role “element” shall be the set
of GM_Primitives contained in this GM_MultiPrimitive. The attribute declaration here specializes the one at
GM_Aggregate to include only GM_Primitives in this type of aggregate.

**IO_IdentifiedObjectBase**
Supplementary identification and remarks information for a CRS or CRS-related object.
-> Please note: This class is defined in ISO 19111:2007, not in ISO 19103. Needs to be changed in the specification.

**TM_Duration**
A data type to be used for describing length or distance in the temporal dimension.

**Comment by cmheazel** [comment]
Definitions have been applied and merged.
