### ISSUE TITLE
Proposed Editorial Changes

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/CityGML-3.0CM#171]
This issue collects proposed changes from other issues which have not been addressed yet. By consolidating these changes in one issue the original issues can be closed.

**Comment by cmheazel** [comment]
Nobu Ishimaru issue #160: I think the font size in the UML figures is too small to read. Is there any way to make them larger? (e.g. link to large image?)

**Comment by cmheazel** [comment]
Chuck Heazel issue #154: Rotate the following images 90 degrees to make them more readable: 14, 17, 18, 19, 21, 29, 40, 48, 56, 59, 62

**Comment by TatjanaKutzner** [comment]
Tatjana Kutzner comments to redlines from Carl Reed #161: 
- p. 11 The links to the citations of 3D Tiles and 3DPS don't work.
- p. 38: "The concept of generic objects and attributes enables the runtime extensions of CityGML applications": This is not clear to me. It implies to me that there are specific runtime extensions that already exist and have already been explained previously in this document. It does not imply to me that CityGML can be extended during runtime. Or is it more common to speak of runtime extension in the English language?

**Comment by TatjanaKutzner** [comment]
Chuck Heazel issue #155: The link /req/generics/use does not work.

**Comment by cmheazel** [comment]
March 1, 2021 SWG meeting: Since we now have a Users Guide we have a place to put more detailed views of the model.  We will leave the figures in the Standard as-is and provide more detailed views in the Users Guide as needed.

**Comment by cmheazel** [comment]
March 1, 2021 SWG meeting: It it the belief of the SWG that the remaining issues have been addressed.  C. Heazel has taken the action to validate and make any necessary corrections.

**Comment by cmheazel** [comment]
@TatjanaKutzner I see the issue with "runtime" on P38.  Consider this alternative:
  "The concept of generic objects and attributes allows application-specific concepts to be represented in the CityGML model"

**Comment by TatjanaKutzner** [comment]
@cmheazel The application-specific concepts are not represented in the CityGML model, but added to CityGML at runtime, e.g. to the GML instance document without adding the concepts to the GML application schema; thus, the information on runtime should not get lost.

How about this:
"The concept of generic objects and attributes allows application-specific concepts to be represented in CityGML at runtime"

**Comment by cmheazel** [comment]
@TatjanaKutzner Consider it done!
Also fixed similar text in the Users Guide
