### ISSUE TITLE
broken url

### ISSUE THREAD

**Issue by mcingotti** [opengeospatial/CityGML-3.0CM#173]
Hi as you can see the XML schemas and example datasets url results in page not found

![Screenshot (161)](https://user-images.githubusercontent.com/43775440/200247078-309c601f-14df-474d-a63f-d7351c215ad0.png)

**Comment by TatjanaKutzner** [comment]
The GML encoding of CityGML 3.0 moved to a new github repository.
You can find everything including the XML schemas and example datasets now here: https://github.com/opengeospatial/CityGML3.0-GML-Encoding

**Comment by mcingotti** [comment]
Thank you!

Maybe it could be better to replace the link here

![Screenshot (162)](https://user-images.githubusercontent.com/43775440/200277735-0acfdf49-0835-47d4-83dd-0db835f992a0.jpg)

**Comment by TatjanaKutzner** [comment]
Thanks a lot for the hint. 
I updated the link.
