### ISSUE TITLE
CRS in class TextCoordGen

### ISSUE THREAD

**Issue by TatjanaKutzner** [opengeospatial/CityGML-3.0CM#19]
In CityGML 2.0, the element worldToTexture can make use of the _gml:SRSReferenceGroup_ attributes to define its CRS.
```
<app:TexCoordGen>
    <app:worldToTexture srsName="…">
      -0.4 0.0 0.0 183550.0 0.0 0.0 0.3333 -37.3333 0.0 0.0 0.0 1.0
  </app:worldToTexture>
</app:TexCoordGen>
```
The use of the CRS has not been modelled in the CityGML 2.0 UML model.

In CityGML 3.0 the use of the CRS is modelled in this way:
![grafik](https://user-images.githubusercontent.com/5949401/45353249-ad400a80-b5ba-11e8-8a43-4e9ca1664928.png)
This results in a different encoding, i.e. now the element TextCoordGen makes use of the gml:SRSReferenceGroup attribute to define a CRS:
```
<app:TexCoordGen srsName="…">
  <app:worldToTexture>
      -0.4 0.0 0.0 183550.0 0.0 0.0 0.3333 -37.3333 0.0 0.0 0.0 1.0
  </app:worldToTexture>
</app:TexCoordGen>
```

**Comment by TatjanaKutzner** [comment]
This differing encoding does not make a semantic difference, thus, it should be fine, as it is now.

**Comment by 3DXScape** [comment]
Are there any contrary opinions?

**Comment by TatjanaKutzner** [comment]
In the web conference on 17 May 2019 we agreed that the different encoding is fine.
