### ISSUE TITLE
Space boundaries in IFC

### ISSUE THREAD

**Issue by hlg** [opengeospatial/CityGML-3.0CM#2]
The conceptual model document, page 3, says: "Because the relationship between spaces and their boundaries is now explicitly modeled in CityGML, e.g. a wall object inside a building can refer to the respective bounding InteriorWallSurface objects. This goes beyond the capabilities of IFC and is very suitable to represent BIM-as-Built models." Just as a remark, these capabilities are there in IFC as well, though they are probably not modelled in exactly the same way. That is because this information is necessary already in the planning phase, e.g. for thermal energy simulations or to assign surface related activities such as painting to rooms in construction schedules.

**Comment by TatjanaKutzner** [comment]
The issue was discussed in the web conference on 13 June, 2019. We will take care of the comment in the specification.
