### ISSUE TITLE
ADE Hooks

### ISSUE THREAD

**Issue by TatjanaKutzner** [opengeospatial/CityGML-3.0CM#20]
In CityGML 2.0, every feature type provides one hook.
In CityGML 3.0, several feature types provide up to three hooks due to the mixin classes. The BuildingType definition, for instance, contains three hooks:
```
<complexType name="BuildingType">
  <complexContent>
    <extension base="core:AbstractTopLevelCityObjectType">
      <sequence>
        ...
        <element maxOccurs="unbounded" minOccurs="0" 
              ref="AbstractGenericApplicationPropertyOfAbstractBuilding"/>
        ...
        <element maxOccurs="unbounded" minOccurs="0" 
              ref="AbstractGenericApplicationPropertyOfAbstractConstruction"/>
        ...
        <element maxOccurs="unbounded" minOccurs="0" 
              ref="AbstractGenericApplicationPropertyOfBuilding"/>
      </sequence>
    </extension>
  </complexContent>
</complexType>
```

In CityGML 2.0, the hook elements were always the last element in the complexType definition.
Now in 3.0, the hook elements are scattered throughout the complexType definition, because ShapeChange first writes all attributes from the AbstractBuilding class, then all attributes from the AbstractConstruction class, and finally all attributes from the Building class.

**Comment by TatjanaKutzner** [comment]
I think, it is necessary that the BuildingType definition provides all these hooks, otherwise additional properties added to AbstractBuilding or AbstractConstruction within an ADE cannot be added to Building objects in instance documents.

**Comment by 3DXScape** [comment]
Any contrary opinion(s)?

**Comment by clausnagel** [comment]
I would prefer one hook per feature. Seems to be another good reason why we should avoid multiple inheritance and mixin classes (see #9 and #32)

**Comment by TatjanaKutzner** [comment]
In the web conference on 17 May 2019 we discussed that the problem has been solved in the meantime, as we no longer make use of multiple inheritance. Thus, this issue is no longer relevant.
