### ISSUE TITLE
CityGML3 additional complexity (vs v2 model) + migration from v2 to v3

### ISSUE THREAD

**Issue by EmDevys** [opengeospatial/CityGML-3.0CM#23]
Version 3 model is more Complex (though apparently with a better/clearer structure) than v2 model. There are additional concepts / modules in the model, key ones being:
- 2 pivotal abstract classes Space and SpaceBoundary
- New Construction module + BuildingConstructiveElement (IFC) + OtherConstruction (INSPIRE) + ConstructionVoid + ConstructionOpeningSurface (and their relation – which is unclear in the documents made available – clarification required) - with the example of Windows and Doors.
- new class AbstractToplevelCityObject
- new class AbstractBuildingSubdivision 
- New Versioning module
- Geometric / Thematic / Topologic SpaceRelation / BoundaryRelation, which should be clarified.
These new elements in the model should be presented and clarified, in order to facilitate understanding, accetpance and implementation. Guidance should be provided on how to handle these elements from v2 CityGML.
Note: In some ”close future” (when the model is finalized), hopefully migration tools would help.

Such documentation + clarifications + guidance on the migration from v2 to v3 should be provided.

**Comment by 3DXScape** [comment]
The chairs will ask for presentations on any/all of these topics at the Charlotte TC meeting

**Comment by TatjanaKutzner** [comment]
In the web conference on 13 June, 2019, we discussed that this will be the next step. Now that we have reached a rather stable data model, the next step will be to add definitions to the data model.
