### ISSUE TITLE
Potential redundancy between attributes validFrom and validTo of AbstractFeatureLifeSpan, and dateOfConstruction and dateOfDemolition for AbstractConstruction 

### ISSUE THREAD

**Issue by EmDevys** [opengeospatial/CityGML-3.0CM#24]
The feature type AbstractFeatureLifeSpan has the attributes validFrom and   validTo, that are related to the real world and come from some INSPIRE themes   (e.g. Transport)   The feature type AbstractConstruction has the attributes   dateOfConstruction and dateOfDemolition, that are also used in INSPIRE theme   Buildings.       This creates some duplication of information.

The use of these respective attributes is to be clarified. Likely, use only one set of attributes at convenient level.

**Comment by TatjanaKutzner** [comment]
Relates to #1. See comment there about the discussion in the Modelling Subgroup.
