### ISSUE TITLE
Use of new attributes occupancyDaytime and occupancyNighttime for AbstractSpace

### ISSUE THREAD

**Issue by EmDevys** [opengeospatial/CityGML-3.0CM#25]
The feature type AbstractSpace has attributes occupancyDaytime and   occupancyNighttime, defined as integer.       Likely, it is number of occupants?   Very useful information but not easy to maintain. Likely relevant only   for spefic buildings (hospitals, ...).

It is proposed to provide clear definition and possibly some guidelines  or examples about when it is relevant to capture it.

**Comment by TatjanaKutzner** [comment]
Has been improved. See issue #62.
We agreed in the web conference on 18 April 2019 that occupancy needs a proper documentation.
