### ISSUE TITLE
Cardinality of relation between ConstructionSpace and AbstractConstructionsurface : need for clarification

### ISSUE THREAD

**Issue by EmDevys** [opengeospatial/CityGML-3.0CM#26]
Cardinality   of relation between ConstructionSpace and AbstractConstructionsurface is 0..2   for Construction Space (which may be considered as a limitation).

Consider providing an explanation for this limitation

**Comment by TatjanaKutzner** [comment]
The cardinality was changed to * after discussion at the OGC TC Meeting in Fort Collins, June 2018, see commit edb013404ac4544ebd145ee7187c2121dc42c4bf.
