### ISSUE TITLE
use of attributes dateOfConstruction, dateOfRenovation and dateOfDemolition for AbstractConstruction: allow for time interval

### ISSUE THREAD

**Issue by EmDevys** [opengeospatial/CityGML-3.0CM#27]
The feature type AbstractConstruction has the attributes   dateOfConstruction, dateOfRenovation and dateOfDemolition, that are also used   in INSPIRE theme Buildings.       INSPIRE offers the possibility to document these dates, either as a date   or as an interval.   The interval may be useful for the construction date of old buildings   where information has uncertainties (e.g. between 1900 and 1950) or for new   buildings [buildind permit, end of construction].

=> Consider offering the possibility to provide building events as dates or as date intervals.

**Comment by TatjanaKutzner** [comment]
Will be further discussed as part of #53. One idea there is to use codes for adding additional information about the renovation of objects. These codes could also be used to model time intervals.
