### ISSUE TITLE
use of MultiSurface for the description of the Building in CityGML v2 vs v3

### ISSUE THREAD

**Issue by EmDevys** [opengeospatial/CityGML-3.0CM#28]
In CityGML, at LOD2+, the use of MultiSurface for the description of the Building was (apparently) encouraged by the CityGML 2.0.
In v3, it seems that the question is whether lod2Solid/ lod3Solid should be mandatory, and lod2MultiSurface/ lod3MultiSurface only for additional geometry.
If this is correct, this would be a significant change between v2 and v3, which might not facilitate conversion of CityGML data sets from v2 to v3.
Guidance on this to be provided, taking into account the need to convert existing v2 data into v3, as well as CityGML production rules for the future.

**Comment by clausnagel** [comment]
I would not agree that CityGML 2.0 favors MultiSurface representations of buildings for LOD2 or higher. Where do you read this in the specification? Most of the newly created LOD2 building models that I come across rather use Solid representations. 

Nevertheless, the current draft of the CityGML 3.0 conceptual model still offers both MultiSurface and Solid representations for buildings. And I would agree that it is important to keep this choice.

**Comment by TatjanaKutzner** [comment]
In today's web conference we confirmed that there won't be a change in policy on how to deal with the representation of buildings using Solid and MultiSurface.
The current draft of the CityGML 3.0 conceptual model only enforces Solid for LoD1, whereas LoD0/2/3 can be represented using Solid and MultiSurface.

**Comment by TatjanaKutzner** [comment]
Issue did not lead to further discussion since the last two webconferences and, thus, is considered resolved and will be closed.
