### ISSUE TITLE
definition & use of attributes ”elevation” of type ”heightAboveGround” for feature types Room and AbstractBuildingSubdivision

### ISSUE THREAD

**Issue by EmDevys** [opengeospatial/CityGML-3.0CM#29]
The feature types Room and AbstractBuildingSubdivision have an attribute called ”elevation” and of type ”heightAboveGround”.
This is to be clarified.
It is recommended to 
- Provide a definition for these attributes.
- Choose relevant attribute name and type.

**Comment by TatjanaKutzner** [comment]
Was resolved in commit edb0134. 
- Feature Type AbstractBuildingSubdivision: attribute "elevation" is now of type "Elevation"
- FeatureType Room: attribute "elevation" was changed to "roomHeight" of type "RoomHeight"
