### ISSUE TITLE
Building / Building part model

### ISSUE THREAD

**Issue by volkercoors** [opengeospatial/CityGML-3.0CM#31]
yesterday, we had a nice presentation on Building / Building Part modelling in different standards from Sweden at the 3D GeoInfo. 

https://www.int-arch-photogramm-remote-sens-spatial-inf-sci.net/XLII-4-W10/27/2018/

Based on the discussion with Helen afterwards, I noticed that in the CityGML 3.0 Building Model draft, there is a multiple inheritance.  I understand the reason for this (to avoid BuildingParts at the top level CityObject as well as recusive building parts), but multiple inheritance is difficult to implement in many languages (Java only supports it vis Interface etc.) I should be avoided. I’ll also open an issue on it on github. Please comment.

![citygml building-buildingpart](https://user-images.githubusercontent.com/5288711/46341115-b0696c00-c637-11e8-9753-02554e83f99f.png)

Regards
     Volker

**Comment by volkercoors** [comment]
(thomas Kolbe via email:

the link to the paper is interesting and I also discussed with
Helen and Lars afterwards. 

Using multiple inheritance is standard in geoinformation domain 
modeling and is being used e.g. in INSPIRE and the German AAA 
models. There is a dedicated mechanism
to make clear which class in the mapping to code and
exchange formats should become the "real" (and only) superclass. 
All other classes are being marked and handled as so-called
"mix-in" classes. 

Best regards
Thomas

**Comment by volkercoors** [comment]
but this specific issue can be solved without multiple inheritance if I am right:

Issue: Building Part shall not be a top level feature. 
This is the case in CityGML 2.0 XSD schema, in addition, there is a conformance requirement that basically says that it is not allowed to have a BuildingPart without a building – see CityGML Quality Interoperability experiment. Disadvantage of this solution ist hat is it not valided – so it is ignored mot of the time.

Solution without Multiple Inheritance:

A Building is an Abstract Building
A BuildingPart is an AbstractBuilding
A Building consists of 0 to many BuildingParts
A BuildingPart has exactly one Building (this is essential as a Building Part cannot extist without a Building any more).

Or sketched in UML (see appendix).

I will copy this to  GitHup issue this  time. We should decide how to use github in future for such discussions.

And by the way, INSPIRE tries to reduce the multi heritance as well, see presentation of Giacomo on the mapping of CityGML tot he INSPIRE 3D building model at the INSPIRE conference two weeks ago.

Regards
      Volker
![buildingpart](https://user-images.githubusercontent.com/5288711/46347669-abfb7e00-c64c-11e8-904f-87156029279f.jpg)

**Comment by volkercoors** [comment]
Dear Volker,

at least Building will need to inherit both
from AbstractTopLevelCityObject and
at the same time from AbstractBuilding,
so there is no way to get around the multiple
inheritance (if you do not want to copy all 
attributes from AbstractBuilding to BuildingPart).

Best regards
Thomas

**Comment by volkercoors** [comment]
Abstract Building can inherit from AbstractTopLevelCityObject.   Similar as in CityGML 2.0. No multiple inheritance in this case, and still BuildingPart always need a building. Easy.

**Comment by volkercoors** [comment]
short summary of a discussion of Volker and Thomas at 3DGeoInfo.

agreed that buildingPart exclusively belongs to one building:
 "*" becomes a 1 
A Building has 0 to many BuildingPart ("*")
A BuildingPart belongs to exactly one Building (1)
Aggregation becomes a composition

multiple inheritance will be discussed in another issue.

**Comment by TatjanaKutzner** [comment]
I modified the UML model as suggested above:
![grafik](https://user-images.githubusercontent.com/5949401/47027545-e9412f00-d167-11e8-95ab-dcb47e0186dd.png)
commit https://github.com/opengeospatial/CityGML-3.0CM/pull/17/commits/8e2715cdc123418aafa08515618c734188c8c132

**Comment by 3DXScape** [comment]
Any other proposals? Can we adopt this?

**Comment by clausnagel** [comment]
Resolved in draft release [3.0.0-draft.2018.12.17.1](https://github.com/opengeospatial/CityGML-3.0CM/releases/tag/3.0.0-draft.2018.12.17.1)
