### ISSUE TITLE
ClosureSurface and VoidSurface

### ISSUE THREAD

**Issue by TatjanaKutzner** [opengeospatial/CityGML-3.0CM#49]
The Core module currently defines a ClosureSurface and a VoidSurface. Can they be considered as semantically equivalent so that only one of them is enough or should we keep both classes?

**Comment by clausnagel** [comment]
Do we have a common understanding of `Void` and `VoidSurface`? See #22. Well, at least it is not sufficiently clear to me, so I do not feel like I could answer this question.

**Comment by TatjanaKutzner** [comment]
In the web conference on 28 March 2019 we agreed that the issue has become obsolete, as it was decided in issue #22 to generally drop Void and VoidSurface from the model.
