### ISSUE TITLE
Normals of solids and shared surfaces

### ISSUE THREAD

**Issue by hlg** [opengeospatial/CityGML-3.0CM#5]
Previously, I found in the CityGML 2.0.0 specification that room surfaces should have their normals point outward of the room (into the constructive elements) given that the room was modelled as a solid. Since in this case interior thematic surfaces should reference the respective parts of the room solid geometry (according to the standard), the thematic surface normals would also point into this direction with the counter-intuitive result that textures would have to be applied to the back of the surfaces. Now, for the new constructive elements with solid geometry, this would be the other way round, normals pointing more intuitively outward of the constructive element (occupied space) into the room (unoccupied space). The result is however that the boundary surface can not be shared between room and constructive element (because of the different orientation) and it must be decided which of the two surfaces to use for the thematic surfaces. Am I missing something?

**Comment by TatjanaKutzner** [comment]
In the last web conference on 18 April 2019 we agreed that we will follow the same approach as in CityGML 2.0, see the example here: http://schemas.opengis.net/citygml/examples/2.0/building/Building_LOD4-EPSG25832.gml

The solid geometry of the room is defined by orientable surfaces that reference the polygons of the thematic surfaces. 
The orientable surfaces are reversed, i.e. they point outwards the room, whereas the surface normals of the thematic surfaces point inwards the room.

We will check whether FME supports orientable surfaces and xlinks within orientable surfaces.
