### ISSUE TITLE
Additional attribute requirements for the CityGML 3.0 building module

### ISSUE THREAD

**Issue by TatjanaKutzner** [opengeospatial/CityGML-3.0CM#51]
At the OGC TC Meeting in Southampton, September 2017, we asked for suggesting additional attribute requirements for the CityGML 3.0 building module. 
The additional attributes that were suggested are listed here: https://docs.google.com/spreadsheets/d/1ArGP62suqQJbToWKMea0emMMHv_GqEcpN1kk1ssDd2E/edit?usp=sharing
These suggestions still need to be discussed.

**Comment by ennioVisco** [comment]
I'll attach the link [here ](docs.google.com/spreadsheets/d/1ArGP62suqQJbToWKMea0emMMHv_GqEcpN1kk1ssDd2E) for the benefit of the readers, as links don't work in images 😂

**Comment by TatjanaKutzner** [comment]
Sorry, the link should work now correctly.

**Comment by volkercoors** [comment]
discussion 7.2.2019 (issue #6): attribute to indicate the area / percentage of a surface that is shared by another surface (without explicitly model the geometry).

**Comment by TatjanaKutzner** [comment]
In the web conference on 21 February 2019 we started to discuss the various suggested attributes.

The attributes could, for instance, be provided as property sets. Property sets could be used to group attributes according to different use cases. The property sets can then be mapped to CityGML using generic attributes, or, ADEs could be used to define property sets, i.e. the ADE would consist of one subclass that contains all the attributes.
Possible rule: If an ADE only consists of additional attributes, then the ADE fulfils the criteria of a property set.

However, some of the attributes are so generic/common that they should be made available in the model directly.
In particular, we decided to add the suggested attributes on volume and various area values, as they are required for many areas of application. To keep the list of additional area attributes short, we opted for defining an attribute "area" of the data type "QualifiedArea" which then provides the area value and the type of area value (wallSurfaceArea, roofSurfaceArea, wallGlazingArea, etc.) The same is done for the volume information. See commit 90c521e3b137e7b03434a5d702741339b894d6cd.

**Comment by thomashkolbe** [comment]
In the web conference on the 8th of November 2019 we went through the table. All but one suggested attributes have been included already in the course of the revisions of the Core, Construction, and Building modules in the course of 2019.  

The only attribute that is not going to be included is `obstacle:Boolean[0..1]` for the `Building` class. This attribute was suggested to indicate wether a building is an obstacle with regard to flight control. The attribute is very application specific and, hence, should be represented in a possible CityGML ADE for flight control or as a generic attribute. 

This issue will be closed on 2019-11-12.
