### ISSUE TITLE
Replicated Attributes

### ISSUE THREAD

**Issue by ennioVisco** [opengeospatial/CityGML-3.0CM#52]
Hello,

it appears to me that the attributes 
- class
- function
- usage

are replicated in a lot of classes. I was wondering if anyone ever considered to generalize them in perhaps the new _AbstractConstruction_ class or any other.

**Comment by TatjanaKutzner** [comment]
Relates to #10

**Comment by TatjanaKutzner** [comment]
The attributes need to be provided separately for each class, because their data types are code lists. According to the decision made in #10 an empty code list class is defined for every code list and these code list classes are then used as attribute types of class, function, and usage.
