### ISSUE TITLE
attribute renovation for construction elements 

### ISSUE THREAD

**Issue by volkercoors** [opengeospatial/CityGML-3.0CM#53]
renovation date for construction elements - reason of renovation should be stored 
see Energy ADE: http://en.wiki.energy.sig3d.org/index.php/Main_Page 

OR 
more General: important Event in the life time of a Building.
construction, renovation, demolition, 

Date, meaning, free text?

**Comment by volkercoors** [comment]
issues #27 "consider offering the possibility to provide Building Events"...

**Comment by TatjanaKutzner** [comment]
In the web conference on 7 March 2019 we discussed and decided on removing the attribute _dateOfRenovation_.
Instead, we will add an attribute _constructionEvent_ with multiplicity [0..*] that allows for defining the type of event (attribute _event_) via values defined in a code list (e.g. building permit, start of renovation, end of renovation), the date of event (attribute _dateOfEvent_) and for providing additional information on the event (attribute _description_).
