### ISSUE TITLE
Vertical stacking of building parts

### ISSUE THREAD

**Issue by phtj** [opengeospatial/CityGML-3.0CM#58]
Buildings with 'parts' that are stacked on top of each other are common. 

As an example, we can consider Pacific Place in Hong Kong.
http://1.bp.blogspot.com/-sBOZHP2jbHc/ToK8jbfXFbI/AAAAAAAAAlc/EGc4u2wnnCw/s1600/Pacific%2BPlace.jpg

https://www.google.com/url?sa=i&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwjNgobpg9vgAhUUTo8KHWScC2IQjRx6BAgBEAU&url=http%3A%2F%2Fwww.heatherwick.com%2Fproject%2Fpacific-place%2F&psig=AOvVaw0EB9Hn-Gk-5C3pjyqc2IuJ&ust=1551326529735086

There is a podium with multiple towers, and the space ontop of the podium is a space that is accessible to the public. The towers are each separate buildings. The location of the ground plane is quite ambiguous since there are multiple levels that feel like the ground. The actual ground is somewhere deep down under the underground car parking levels.

Another example might be the Marina Bay Sands in Singapore. 
https://www.marinabaysands.com/content/dam/singapore/marinabaysands/master/main/home/Revamp/new-homepage/offers/new_welcome-offers_v1.jpg

The concepts of building, building part, building unit, storey, do not seem to fit very well for these types of building.  It seems that the current definition of building part is that it must be in contact with the ground. In hight density cities, the groundplane is often a very ambiguous concept, so it is not clear if something is in contact with the ground.

**Comment by hlg** [comment]
Comment moved to #8, this issue can be closed.
