### ISSUE TITLE
Construction element interior surfaces

### ISSUE THREAD

**Issue by hlg** [opengeospatial/CityGML-3.0CM#6]
For the constructive elements, I would imagine two ways to approach the geometric modelling. On one hand they could be modelled as solids including all surfaces of the respective element. On the other hand they could be modelled as a multisurfaces including only the accessible parts of their surfaces (those touching unoccupied space), omitting the surfaces where constructive elements touch each other and thus hiding construction details. The latter would still be useful in order to model the relation between the two sides of a wall for instance without the full solid geometry of that wall. In the former case, however, would the construction element surfaces touching other construction elements be assigned a thematic surface type and if so which one? (Imagine for instance a wall touching a slab).

**Comment by TatjanaKutzner** [comment]
In the Modelling Subgroup we discussed that there is no need to introduce a new surface type, we can represent touching surfaces by reusing the existing surfaces and express their relation using the relation types from the Core module. The surface can be split up into touching and non-touching parts, the touching part having the topological relation "Equals", or, when the surface is not split up, then the topological relations "Overlaps" or "Covers" can be used.

We will add sketches to github showing the two ways.

To know also in the second case the size of the touching surface area, an attribute "sharedSurfacePart" could be added to the class "AbstractConstructionSurface" to store the total number of surface shared. This will be discussed as part of issue #51.

**Comment by TatjanaKutzner** [comment]
In the Modelling Subgroup we agreed that we need to include in the specification a detailed description of the three concepts and give clear recommendation when to use which concept.

We will create a drawing showing the differences of the concepts.

In addition, we will try to get feedback from the CityGML SWG group at the next OGC meeting in Singapore on these concepts.

**Comment by TatjanaKutzner** [comment]
Please find here sketches that illustrate the two possibilities of representing touching surfaces using relation types.
[Representation of touching surfaces.pdf](https://github.com/opengeospatial/CityGML-3.0CM/files/2992042/Representation.of.touching.surfaces.pdf)

**Comment by TatjanaKutzner** [comment]
At the web conference on 28 March 2019 we agreed on closing the issue.
However, we will complement the sketches by an example of touching constructive elements and by an example where one polygon overlaps two or more other polygons.

We also discussed on how flexible the specification should be regarding the modelling of buildings/building parts as solids and/or multi surfaces.
We agreed on providing recommendations in the specification and pointing out advantages of modelling building parts as closed solids, however, we do not define strict limitiations in the specification by default.

**Comment by TatjanaKutzner** [comment]
Complemented sketches:
[Representation of touching surfaces.pdf](https://github.com/opengeospatial/CityGML-3.0CM/files/3042594/Representation.of.touching.surfaces.pdf)
