### ISSUE TITLE
Namespace of association "genericAttribute" in the "Generics" module

### ISSUE THREAD

**Issue by thomashkolbe** [opengeospatial/CityGML-3.0CM#68]
The association "genericAttribute" is part of the "Generics" module, but in the derived GML3 encoding it seems that it resides in the "Core" namespace (instead of the "Generics" namespace). Please check, if the association really belongs to the Generics UML package (and not to the Core) or if this might be a bug / issue when using ShapeChange to derive the GML3 XML schema.

**Comment by TatjanaKutzner** [comment]
We discussed in the web conference on 13 June 2019 how to solve this problem. We decided on discussing this issue with other colleagues who are experienced on UML modelling.

**Comment by TatjanaKutzner** [comment]
I talked to Clemens regarding this issue. 

The association belongs semantically to the `Core` module. `AbstractCityObject.genericAttribute` is a property of `AbstractCityObject` and, thus, belongs according to the UML meta model to the namespace of `AbstractCityObject`.

Regarding modularisation it does not make sense to put `genericAttribute` into the `Generics` namespace. This would mean that the `Core` module always imports the `Generics` module (and the `Generics` module, in turn, imports the `Core` module again). In terms of modular specifications the `Core` and `Generics` modules would then represent one conformance class and one package in UML.

In the web conference we discussed that one solution could be to add a subclass of `AbstractCityObject` to the `Generics` module and to define the assocation between the subclass and `AbstractGenericAttribute`.
This can solve our specific problem.

However, from Clemens' point of view the best solution would be to move the class `AbstractGenericAttribute` to the `Core` module. The derived classes remain in the `Generics` module.

**Comment by clausnagel** [comment]
Well, I would prefer the latter solution for all dependencies that we have. For instance, the `Core` module is dependent on the `Appearance` module due to the `appearance` association between the `AbstractCityObject` and `Appearance` classes. This can also be resolved by defining an `AbstractAppearance` class in the `Core`. 

Similar dependencies exist from the `Core` to the `Dynamizer`, `PointCloud` and `Versioning` modules.

In CityGML 2.0, the dependencies were only resolved on the level of the GML application schema by using the ADE hook property of `_CityObject`. I agree that we should rather avoid this solution for CityGML 3.0

**Comment by thomashkolbe** [comment]
I would also agree to go ahead using the latter approach to avoid package dependencies from the `Core` module to the other modules.

**Comment by TatjanaKutzner** [comment]
I implemented this approach for the `Generics` module and the `Appearance` module.

In the `Appearance` module I had to move the `AbstractAppearance` class and the `AbstractSurfaceData`  class to the `Core` module to avoid the package dependency.

`PointCloud` module: This module consists of the class `PointCloud` only. When moving this class to the `Core` module, does it still make sense to keep the module?

`Dynamizer` module: Will require to move the classes `Dynamizer`, `SensorConnection`, and `AbstractTimeseries` to the `Core` module.

`Versioning` module: Will require to move the whole module to the `Core` module.

**Comment by TatjanaKutzner** [comment]
There is a different approach that does not require moving classes from the thematic modules to the `Core` module.
For each of the thematic classes `Appearance`, `Dynamizer`, `AbstractGenericAttribute`, `PointCloud`, `Version`, and `VersionTransition` corresponding abstract classes are defined in the `Core` module: `AbstractAppearance`, `AbstractDynamizer`, `AbstractGenericAttribute`, `AbstractPointCloud`, `AbstractVersion`, and `AbstractVersionTransition`. By modelling the thematic classes as subclasses of the abstract classes, package dependency can be avoided as well.
This approach has now been implemented.
