### ISSUE TITLE
Geometries of nested occupied and unoccupied spaces

### ISSUE THREAD

**Issue by hlg** [opengeospatial/CityGML-3.0CM#7]
The concept of occupied / unoccupied spaces is interesting, but I am wondering about the consequences in terms of the geometry and topological model behind it, especially when they are nested. For example (case 1) if an unoccupied space is located inside an occupied space, e.g. opening/void in constructive element or room inside building, is the implied Boolean operation of subtraction assumed to be already carried out in the geometry to be included in the model or is to be carried out by downstream applications? That is, does the geometry of the occupied space have a "hole" in it to accommodate the unoccupied space? The other way round (case 2), if an occupied space (e.g. building installation) is contained in an unoccupied space (e.g. room), is this "cut out" of the unoccupied space? I can imagine cases where it would be more natural to do one or the other, but would expect some consistent approach for the conceptual model.

**Comment by volkercoors** [comment]
has some tested such concepts of occupied / unoccupied spaces?
A simpe case would be a building with a door (wallsurface with polygon with no interior ring) and a window (wall surface with polygon with interior ring) and two rooms inside the building. How is the geometry of the building itself modelled in this case? Following the concept of CityGML for polygons (polygon with hole), it will a a soild with to holes. It can be specified as such in CItyGML, but I have not seen it in any existing citygml document yet. I am also not aware of any test data set, so I do not know if the available software tools support this kind of geometry. 
And, please calculate the volume of such a building with existing software such as FME! The volume of the solid building geometry + the volume of the rooms should be what we usually call the volume of the building. 

Hint: a wrong face orientation in a solid geometry has a big impact on volume calculation, so it is likely that a room / any "unoccupied space" modelled as solid geometry have a negative volume... at least if you want to see the walls of the room from inside the room (and do not cheat by using double sided lighting).

see my slide on CityGML quality management, OGC TC meeting Sep 2019 / opening:
https://portal.opengeospatial.org/files/?artifact_id=80718, slide 17-18. Volume calculation was done in FME.

**Comment by TatjanaKutzner** [comment]
In the web conference on 28 March 2019 we decided on disallowing that solids can have interior holes. Any space inside a building should be modelled as unoccupied space; inside these unoccupied spaces, in turn, occupied spaces can occur (e.g. furniture).

As a general rule for volume calculation, subtract everything that is unoccupied (e.g. subtract rooms from building) and add again everything that is occupied inside (e.g. add installation inside rooms).
For simply calculating the volume of the building, the unoccupied spaces can be ignored.
