### ISSUE TITLE
A role name is missing at the association between AbstractConstruction and AbstractConstructionSurface

### ISSUE THREAD

**Issue by yaozhihang** [opengeospatial/CityGML-3.0CM#72]
The association between `AbstractConstruction` and `AbstractConstructionSurface` should be Bi-directional. It seems that an arrow at the association end pointing to the `AbstractConstruction` is missing in the current UML diagram. This would result in a problem of XML-encoding when using ShapeChange, see here 
https://github.com/opengeospatial/CityGML-3.0Encodings/blob/master/CityGML/Schema/construction.xsd#L75
```
  <complexType abstract="true" name="AbstractConstructionSurfaceType">
    <complexContent>
      <extension base="core:AbstractThematicSurfaceType">
        <sequence>
          <element maxOccurs="unbounded" minOccurs="0" name="fillingSurface" type="con:AbstractFillingSurfacePropertyType"/>
          <element maxOccurs="unbounded" minOccurs="0" name="closureSurface" type="core:ClosureSurfacePropertyType"/>
          <element maxOccurs="unbounded" minOccurs="0" ref="con:AbstractGenericApplicationPropertyOfAbstractConstructionSurface"/>
        </sequence>
      </extension>
    </complexContent>
  </complexType>
```
Above, we can see that the property  `construction`  is not encoded in the XML definition of the class `AbstractConstructionSurface`.

**Comment by TatjanaKutzner** [comment]
Associations that represent subsets of the association between _AbstractSpace_ and _AbstractThematicSurface_ are only modelled uni-directional to facilitate implementation. 
For this reason, the property _construction_ is not encoded.

Relates to issue #75.

**Comment by thomashkolbe** [comment]
Can be closed
