### ISSUE TITLE
transformationMatrix should be a mandatory attribute for ImplicitGeometry

### ISSUE THREAD

**Issue by yaozhihang** [opengeospatial/CityGML-3.0CM#73]
In the UML diagram of CityGML 2.0, the multiplicity of the property `transformationMatrix` of the class `ImplicitGeometry` is **_1_**. This is correct, because without transformation matrix, the implicit geometry cannot be properly transformed to the world coordinate system. In the current CityGML 3.0 diagram, the multiplicity is however modeled with **_0..1_**, which might/should be corrected.

**Comment by thomashkolbe** [comment]
You are right, this is a bug and needs to be fixed. Tatjana, would you please update the model accordingly and close this issue?
