### ISSUE TITLE
Association between AbstractSpace and AbstractThematicSurface to be marked as abstract

### ISSUE THREAD

**Issue by TatjanaKutzner** [opengeospatial/CityGML-3.0CM#75]
As a side result of issue #22 we discussed on marking the association between _AbstractSpace_ and _AbstractThematicSurface_ as abstract, because the association is only implemented in the thematic modules.
This still needs to be applied. Enterprise Architect does not allow for marking attributes as abstract. Instead, ShapeChange should be configured in such a way, that only the subsets of this association in the thematic modules are encoded.

**Comment by thomashkolbe** [comment]
This issue should have been resolved by the latest decision to not make the association between AbstractSpace and AbstractThematicSurface abstract.
