### ISSUE TITLE
Attributes class, function, usage for the classes Window and Door

### ISSUE THREAD

**Issue by TatjanaKutzner** [opengeospatial/CityGML-3.0CM#76]
Should the classes _Door_ and _Window_ also define the attributes _class_, _function_, and _usage_, to be able to specify more precisely the type of door (e.g. front door, cellar door, interior door) or window?

**Comment by thomashkolbe** [comment]
I would say yes. We should be consequent in such a way, that each "real world thing" (represented by a Space) should have these three attributes.
