### ISSUE TITLE
Semi-open spaces

### ISSUE THREAD

**Issue by TatjanaKutzner** [opengeospatial/CityGML-3.0CM#77]
The attribute _spaceType_ can be used to define semi-open spaces. How will these semi-open spaces look geometrically, e.g. when modelled as Solid? Or can they only be modelled as MultiSurfaces so that they can be open at the top?

**Comment by thomashkolbe** [comment]
When a semi-open space (like the atrium of a building or a road space) is represented geometrically by a `Solid` geometry, some of the boundary surfaces will be virtual surfaces used to enclose the volume (and to separate it from adjacent spaces). It would be recommended to represent these boundary surfaces by thematic `ClosureSurface` features then.
