### ISSUE TITLE
surfaceMaterial attribute, in Transportation package

### ISSUE THREAD

**Issue by PeterParslow** [opengeospatial/CityGML-3.0CM#78]
The surfaceMaterial attribute exists on the TrafficSpace feature type, which has no (direct) surface property. Wouldn't it be more logical to put it on the TrafficArea feature type?

As it stands, you would need to create a new 'space' at a change of surface material. This may be common practice, but I see no need to break a network representation 'just because' of a change of surface material.

Same for AuxilliaryTrafficSpace / AuxilliaryTrafficArea

**Comment by thomashkolbe** [comment]
You are right, this is a bug and has not been fixed yet. The surfaceMaterial attribute needs to be moved from TrafficSpace to TrafficArea. The same needs to be applied for AuxilliaryTrafficSpace / AuxilliaryTrafficArea.

Tatjana, would you please fix this in the UML diagram and then close this issue?
