### ISSUE TITLE
Texture coordinates and GML 3.3 compact encoding

### ISSUE THREAD

**Issue by clausnagel** [opengeospatial/CityGML-3.0CM#79]
If you want to assign textures to city objects, then both CityGML 2.0 and the current 3.0 draft require that texture coordinates are provided for each boundary ring of a surface geometry. For this purpose, a `app:TexCoordList` element must reference its target rings by their `gml:id`.

GML 3.3 introduces compact encodings for (some) surface objects. Common to these compact encodings is that the `gml:LinearRing` element is omitted as shown in the following example:

```xml
    <gmlce:SimplePolygon>
      <gml:posList>1.0 2.0 3.0 4.0 5.0 6.0 7.0 8.0 9.0</gml:posList>
    </gmlce:SimplePolygon>
```

I do not see how the current texturing mechanism would work in this example. If texturing of `SimplePolygon`s should be supported by CityGML 3.0, then I think the current `Appearance` module needs some rework. Otherwise, it should be made clear that texturing only works with the GML 3.2 encoding of surface geometries.

**Comment by thomashkolbe** [comment]
Wouldn't it be possible that we simply allow that the `app:TexCoordList` element either has to reference a ring (when using the GML 3.2 encoding of surface geometries) or can also reference the `gml:id` of a simplified geometry encoding from GML 3.3? This would work for the example given above (SimplePolygon). However, I have not checked, if this would be applicable to other types of surface encodings offered by GML 3.3.

This would not require any change to the `Appearance` UML model, because the rings are referenced by an URI. We only would have to write in the explanation that these URIs in a CityGML encoding need to unambigously point to the rings bounding the surface and that the first ring always is the outer boundary. In the CityGML GML encoding specification we would then explicitly list allowed target geometry encodings.

**Comment by clausnagel** [comment]
Well, currently `TexCoordList` is defined to point to a linear ring via its `ring` property, not to a surface geometry. The surface geometry is referenced by the `uri` property of `TextureAssociation`. So if we let `TexCoordList` point to the `SimplePolygon` itself, then this already is a change to the appearance module and would affect current implementations. The `SimplePolygon` would then be referenced by both `TexCoordList` and `TextureAssociation`. And it might get confusing if the target of the texture association is a gml:MultiSurface consisting of both simple and non-simple polygons. In this case, the `uri`s of the `TexCoordList` would reference both rings and surface geometries at the same time.

Another solution could be to completely drop the `uri` property from `TexCoordList` . Then we would have to enforce in the specification that the `textureCoordinates` inside `TexCoordList` must be listed in exactly the same order as the rings in the surface geometry. I think almost all exisiting datasets already stick to this anyway. This also would simplify the current `TexCoordList` element. Because in its current form, it also implies an exact same order of the `textureCoordinates` and `ring` elements (this was different in CityGML 2.0, because `ring` was an attribute of `textureCoordinates`).

**Comment by thomashkolbe** [comment]
Ok, dropping the `uri` property from `TexCoordList` looks like a feasible solution. I also have not seen a CityGML 2.0.0 dataset, in which the set of texture coordinate lists are not ordered in the same way as the rings in the referenced geometry.

It can, however, create a problem when there is only one `ParameterizedTexture` feature pointing to a `MultiSurface` or `CompositeSurface`. I believe it is not safe to assume that the different surface members are always stored in the same order. Anyway, is this a practical problem, i.e. have you seen real world datasets with a single texture feature applied to a `MultiSurface` or `CompositeSurface`? If not, we could require that each surface (member) needs to get its own `ParameterizedTexture` feature. But that could increase the encoding size if one `ParameterizedTexture` should be applied e.g. to a TriangulatedSurface.

**Comment by clausnagel** [comment]
In datasets that I come across in practice, `ParameterizedTexture` features really just reference a single `gml:Polygon`. In this [official CityGML 2.0 example dataset](http://schemas.opengis.net/citygml/examples/2.0/appearance/Appearance-EPSG25832.gml), a `gml:CompositeSurface` is referenced. And as you write, if you want to texturize a terrain given as triangulated surface, then this is also an example where you would have to provide texture coordinates for all the triangle members within on `ParameterizedTexture` feature.

Yes, the order of surface members is only fix for a given dataset. So you can make sure that the order of `TexCoordList` elements is identical within the same dataset. If, for instance, this dataset is loaded into a database and exported again, then the export tool would have to make sure that the ordering of the surface members and their texture coordinates does match.

**Comment by thomashkolbe** [comment]
What about making the usage of the `ring` property in `TexCoordList` optional? If `ring` is missing, it would mean that only the reference to the geometry object is provided by the `uri` property and that the order of the rings and the order of `TexCoordList` elements are / need to be the same. This would work for the compact GML 3.3 encodings. If values for `ring` are given, it has the same semantics as in CityGML 2.0.0. We would then include a hint in the specification, that when leaving out the `ring` property, one needs to be especially careful about keeping track of the order of rings and texture coordinate lists in the case of `MultiSurfaces` or `CompositeSurfaces` (incl. `TriangulatedSurfaces`).

**Comment by clausnagel** [comment]
In today's modelling subgroup meeting we agreed that the `ring` property should remain mandatory. We only need to allow that the `ring` property can have an empty value in case of compact geometries that lack the `gml:LinearRing`.

The benefit of this solution is that 
a) it is simple, 
b) the conceputal model doesn't need to be changed and 
c) the conceputal model  remains backwards compatible with CityGML 2.0. 

Here is an example:

``` xml
    <gmlce:SimplePolygon gml:id="id01">
      <gml:posList>1.0 2.0 3.0 4.0 5.0 6.0 7.0 8.0 9.0</gml:posList>
    </gmlce:SimplePolygon>

    ...

    <app:Appearance>
      <app:surfaceData>
        <app:ParameterizedTexture>
          <app:imageURI>image.png</app:imageURI>
          <app:textureParameterization>
            <app:TextureAssociation>
              <app:uri>#id01</app:uri>
              <app:textureParameterization>
                <app:TexCoordList>
                  <app:textureCoordinates>1 1 2 2 3 3</app:textureCoordinates>
                  <app:ring/>  <-- ring is empty because there is no gml:LinearRing
                </app:TexCoordList>
              </app:textureParameterization>
            </app:TextureAssociation>
          </app:textureParameterization>
        </app:ParameterizedTexture>
     </app:surfaceData>
   </app:Appearance>
```
