### ISSUE TITLE
Make TransportationComlex a space

### ISSUE THREAD

**Issue by clausnagel** [opengeospatial/CityGML-3.0CM#82]
It seems that `TransportationComplex` is the last remaining top-level feature type that "is" not a space (by derivation) but that "has" spaces (by aggregation, namely `TrafficSpace`, `AuxiliaryTrafficSapce` and `TransportationSpace`).

For me it would be much more consistent with the other modules if `TransportationComplex` would be modelled as space. Then the thematic surfaces `TrafficArea` and `AuxiliaryTrafficArea` could be directly related to it. `ClearanceSpace` could  also be linked to it (or just be mapped on a `clearanceHeight` property?).

I do not see the additional intention of a `TransportationSpace` compared to `TrafficSpace`.

**Comment by TatjanaKutzner** [comment]
Will be discussed together with issue #64.

**Comment by TatjanaKutzner** [comment]
Has been solved by issue #64.
