### ISSUE TITLE
Some questions about ImplicitGeometry

### ISSUE THREAD

**Issue by clausnagel** [opengeospatial/CityGML-3.0CM#86]
* Why is `ImplicitGeometry` derived from `AbstractFeature`?  In CityGML 2.0 it was just derived from `AbstractGML`. What is the advantage of this change? I think, `ImplicitGeometry` could even be defined to be just a `<<DataType>>`?
* I think it is good that `ImplicitGeometry` now has its own `appearance` property to assign textures or colors to the template geometry. In CityGML 2.0 this was only possible via global appearances. However, in order to reuse the template geometry, another city object still must reference the GML geometry through the `relativeGMLGeometry` property element. Is the appearance implicitly referenced as well? Or do you have to reference all appearances via XLinks as well? I think this can become quite verbose.
    * Alternatively, the geometry and the appearance could be embraced by a new object type. Another city object could then reference this object. In this case, it would be very clear that both the geometry and the appearance are referenced.
* Is it really necessary to be able to inject ADE properties into `ImplicitGeometry`? I cannot think of a use case and would therefore remove the hook element `core:AbstractGenericApplicationPropertyOfImplicitGeometry` from the GML encoding.

**Comment by TatjanaKutzner** [comment]
Point 1) 
Probably, because in CityGML 2.0 the stereotype `<<Object>>` was used that represents an identifiable and distinguishable object. When we started with the ISO-compliant UML model we first used `<<Type>>` instead. As `<<Type>>` is preferably to be used in abstract specifications and not at the application schema level, I probably changed it to `<<FeatureType>>` then.
However, I just had a look at some other classes that originally had the stereotype `<<Object>>`. They use now `<<DataType>>` (e.g. `TextCoordGent`). 
I also think, that we could use `<<DataType>>`, because `ImplicitGeometry` does not need to be an identifiable object.

Point 3)
ShapeChange creates the hook element for every feature type. Thus, when we change the stereotype to `<<DataType>>`, the hook isn't created any more.

**Comment by clausnagel** [comment]
In today's modelling subgroup meeting, we agreed on the following proposal:

1. `ImplicitGeometry` should be changed from `<<FeatureType>>` to `<<ObjectType>>`. This is identical to CityGML 2.0 and ensures that an implicit geometry is an identifiable object with a `gml:id` (like all GML geometries). The `gml:id` is required, for instance, to be able to reference the implicit geometry from a dynamizer. This would not be possible when choosing `<<DataType>>` instead.
2. With `<<ObjectType>>` as stereotype, ShapeChange will not generate ADE hooks.
3. Reusing the GML geometry of another `ImplicitGeometry` requires referencing it from the `relativeGMLGeometry` property using an XLink - just like in CityGML 2.0. If the other `ImplicitGeometry` has appearance, then this appearance is not implicitly referenced, but must be explicitly referenced using another XLink on the `appearance` property. 

The solution proposed in 3) is most flexible, because a user can decide to just reuse the geometry or reuse the geometry plus the appearance. The following snippet shows an example of how to reuse the geometry and the appearance:

``` xml
      <lod2ImplicitRepresentation>
        <ImplicitGeometry>
          <transformationMatrix>1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16</transformationMatrix>
          <referencePoint>
            <gml:Point>
              <gml:pos>1 1 1</gml:pos>
            </gml:Point>
          </referencePoint>
          <relativeGMLGeometry xlink:href="#gml_id_of_template_geometry"/>
          <appearance xlink:href="#gml_id_of_appearance"/>
        </ImplicitGeometry>
      </lod2ImplicitRepresentation>
```

If the `appearance` property is removed from the above snippet, then only the geometry is reused.

**Comment by TatjanaKutzner** [comment]
In addition, we defined an overriding rule for 3) that when an `ImplicitGeometry` has a global appearance and also a local appearance, the local appearance is overriding the global appearance.
