### ISSUE TITLE
AbstractBuilding has BuildingFurniture

### ISSUE THREAD

**Issue by clausnagel** [opengeospatial/CityGML-3.0CM#88]
In the current draft, `AbstractBuilding` has an association to `BuildingFurniture`. In CityGML 2.0, only rooms could have furniture, not the building itself. I prefer the CityGML 2.0 way and would therefore propose to remove this association.

**Comment by thomashkolbe** [comment]
The current proposal is on the one hand a harmonization with other building entities like `BuildingInstallation`, `BuildingConstructiveElement`, and `AbstractBuildingSubdivision`, which all are directly connected to the `AbstractBuilding`. For the GML encoding we could suggest that all `BuildingFurniture` objects have to be represented inline as embedded features of `AbstractBuilding`, and that relations from `BuildingRoom` to `BuildingFurniture` should be expressed just by XLinks. 

On the other hand the current modeling gives the freedom to represent furniture objects, that are known to be within a specific Building(Part), but for which no rooms are known. Also, it would be possible to have furniture on a balcony.
