### ISSUE TITLE
Multiple inheritance

### ISSUE THREAD

**Issue by hlg** [opengeospatial/CityGML-3.0CM#9]
With regard to the introduction of multiple inheritance (mixins), I think that it this is really risky because it compromises the understandability of the schema and complicates implementation of the model in languages without multiple inheritance. IFC has deliberately waived multiple inheritance although the underlying standard for the exchange of product model data (STEP) allows for multiple inheritance. As far as I understand, the mixins are only introduced in order to mark some classes as AbstractToplevelCityObject that can be direct members of the CityModel. Wouldn't it be easier to understand if this (AbstractToplevelCityObject) would be the mixin class ?

**Comment by clausnagel** [comment]
Resolved in draft release [3.0.0-draft.2018.12.17.1](https://github.com/opengeospatial/CityGML-3.0CM/releases/tag/3.0.0-draft.2018.12.17.1)
