### ISSUE TITLE
Small correction to OCL constraint in the PointCloud module

### ISSUE THREAD

**Issue by thomashkolbe** [opengeospatial/CityGML-3.0CM#91]
The `PointCloud` class has an associated OCL constraint which should express that either the points are represented inline (as a `MultiPoint` geometry) or within an external file. The constraint requires that the property `pointFileSrsName` always has to be given for external files. This should be taken out, because formats like LAS or LAZ include georeferencing; only for simple text based formats like XYZ it will be required.

**Comment by TatjanaKutzner** [comment]
The latest commit contains the corrected OCL constraint.
