### ISSUE TITLE
Add LoD 0 surface representation to AbstractThematicSurface

### ISSUE THREAD

**Issue by clausnagel** [opengeospatial/CityGML-3.0CM#92]
`AbstractThematicSurface` objects can currently only be represented by a curve geometry in LoD 0. While this makes sense for some subtypes such as `WallSurface`, I suppose that other thematic surfaces such as `RoofSurface` or `GroundSurface` rather require a surface-based representation also in LoD 0. The same is true, for instance, for `LandUse` objects which are also typically surface-based features.

So, I propose to add a `lod0MultiSurface` geometry property to `AbstractThematicSurface`.

**Comment by thomashkolbe** [comment]
I agree, this was forgotten and the `lod0MultiSurface `geometry property should be added to `AbstractThematicSurface`.
