### ISSUE TITLE
Some issues with the Dynamizer model

### ISSUE THREAD

**Issue by thomashkolbe** [opengeospatial/CityGML-3.0CM#94]
The current version of the Dynamizer module has two issues that need to be revisited:
1. The `SensorConnection` class should be carefully examined, if it can be used to represent links to sensor services that are compliant to the OGC SensorThings API as well as to the OGC Sensor Observation Service (SOS). Also other types of platforms like ThingSpeak, OpenSensors etc. should be supported. It should also become possible to model links to MQTT based sensor services. Furthermore it should be indicated what kind of authentication mechanism has to be used for each specific sensor connection.
2. In the current schema the data models of the OGC standards `TimeSeriesML` and `Observations & Measurements` (O&M) are being imported to enable users to embed `TimeSeriesML` and `O&M` documents within the CityGML file. However, it turned out that for an implementation of the Dynamizer module the entire concepts from the two OGC standards would also need to be implemented, which is not practical. Instead, it should be just possible to link to an external file that is compliant to one of these standards. A very simple encoding of time value pairs that include int, double, appearances, geometries, and ImplicitGeometries should also be supported.

**Comment by TatjanaKutzner** [comment]
Please find attached a revised Dynamizer module that addresses the issues mentioned above: 
[2019_10_28_Dynamizer with code lists.pdf](https://github.com/opengeospatial/CityGML-3.0CM/files/3779383/2019_10_28_Dynamizer.with.code.lists.pdf)

**Comment by kanishk-chaturvedi** [comment]
Please find attached the presentation slides illustrating the usage of the revised Dynamizer module. 

The presentation shows numerous concrete examples of how to connect city objects with sensors and IoT devices registered with the OGC SensorThings API and OGC Sensor Observation Service servers as well as with other popular platforms using HTTP and MQTT protocols. 

The examples are also given on how the results of a solar potential analysis can be represented in different ways and linked with the building surfaces.

[2019_10_29_Dynamizer_Examples.pdf](https://github.com/opengeospatial/CityGML-3.0CM/files/3783398/2019_10_29_Dynamizer_Examples.pdf)

**Comment by hlg** [comment]
In the 31 October meeting some requirement of time periods to not overlap was mentioned. As I remember, this limitation would affect either multiple time series within one dynamizer (`Dynamizer.dynamicData`) or multiple dynamizers referring to the same particular attribute of the same particular object.

I can not find anything related to this in the documents attached to the previous posts. Thus I want to confirm whether it is possible to have multiple alternative time series for the same attribute and the same or overlapping time period. Cases for this would be, for example, measuring the same value with different technology or attaching both simulation results and measured values to one particular object.

It would also be reasonable to deny this possibility and allow for CityGML3 to just describe the state of city objects during their lifetime in one particular existence or reality. This would still very much extend CityGML2 which was limited to describe the state of city objects at one particular point in time.

**Comment by TatjanaKutzner** [comment]
Please find here the latest version of the Dynamizer UML model that is also included in the latest eap file (commit ae8c197) and encoded in the XML schema files (commit https://github.com/opengeospatial/CityGML-3.0Encodings/commit/bb0c6dcddff79208cb227a7092faa80834c76e5f): [2019_11_01_Dynamizer with code lists.pdf](https://github.com/opengeospatial/CityGML-3.0CM/files/3797863/2019_11_01_Dynamizer.with.code.lists.pdf)

The only modification to the previous version is that the attribute `appearanceValue` is now of the type `AbstractAppearance` instead of `Appearance`. In this way no dependency between the `Dynamizer` module and the `Appearance` module exists any more in the XML schema files.

**Comment by thomashkolbe** [comment]
> In the 31 October meeting some requirement of time periods to not overlap was mentioned. As I remember, this limitation would affect either multiple time series within one dynamizer (`Dynamizer.dynamicData`) or multiple dynamizers referring to the same particular attribute of the same particular object.
> 
> I can not find anything related to this in the documents attached to the previous posts. Thus I want to confirm whether it is possible to have multiple alternative time series for the same attribute and the same or overlapping time period. Cases for this would be, for example, measuring the same value with different technology or attaching both simulation results and measured values to one particular object.
> 
> It would also be reasonable to deny this possibility and allow for CityGML3 to just describe the state of city objects during their lifetime in one particular existence or reality. This would still very much extend CityGML2 which was limited to describe the state of city objects at one particular point in time.

The requirement that the time periods for different Dynamizers referring to the same property of the same object do not overlap is important, because no ambiguous statements shall be given regarding the value of a property. For each point in time it must be always possible to determine at most one valid value (if there is no Dynamizer information for a time point, then the value has to be considered as unknown for that time point).

However, you can use the Versioning module and create two alternative versions of the dataset in which different versions of the Dynamizers are referring to alternative sources. The fact that the two versions of the dataset are indeed alternatives (and not just historic changes) can be expressed by setting the property "type" of "VersionTransition" to "fork". Note that not the entire dataset has to be represented redundantly within the alternative versions; it would be sufficient just to change the respective Dynamizer features.

**Comment by thomashkolbe** [comment]
Two more things should be improved in the most recent Dynamizer data model:

1. The properties `firstTimestamp` and `lastTimestamp` of the class `AbstractAtomicTimeseries` should be moved one level higher in the generalization hierarchy (into the class `AbstractTimeseries`), because these attributes are also useful for `CompositeTimeseries`. They would then be inherited by both classes `AbstractAtomicTimeseries` and `CompositeTimeseries`.

2. In the class `TabulatedFileTimeseries` we should give users the choice how to reference a specific column in a tabulated datafile - by column number or column name. Therefore, instead of having the properties `idColumn`, `timeColumn`, and `valueColumn`, we should have the following properties:
`idColumnNo: Integer [0..1]`
`idColumnName: CharacterString [0..1]`
`idValue: CharacterString [0..1]`
`timeColumnNo: Integer [0..1]`
`timeColumnName: CharacterString [0..1]`
`valueColumnNo: Integer [0..1]`
`valueColumnName: CharacterString [0..1]`
The property `idValue` would then specify that only those rows from the file are being selected, where the value in the idColumn matches the specified `idValue`. This allows, for example, to have a large CSV file that has e.g. the solar irradiation values for all thematic surfaces of a city model for each month in a year. In this case, a Dynamizer can be created for each `RoofSurface` or `WallSurface` feature, which all refer to the same CSV file, but using a different `idValue` to select the proper rows from the file for the respective RoofSurfaces and WallSurfaces.

**Comment by TatjanaKutzner** [comment]
Please find here the UML model that includes the above-mentioned things to be improved [2019_11_05_Dynamizer with code lists.pdf](https://github.com/opengeospatial/CityGML-3.0CM/files/3809907/2019_11_05_Dynamizer.with.code.lists.pdf)

**Comment by TatjanaKutzner** [comment]
Based on the discussion in the web conference on 8 November 2019 the following things were updated in the latest commit:
- The data type `URI` was changed to `CharacterString` for the attributes `attributeRef`, `linkToObservation`, and `linkToSensorDescription`, because XPath expressions cannot be encoded as `xs:anyURI`, only as `xs:string`.
- The stereotype of the class `AuthenticationValue` was changed from `<<Enumeration>>` to `<<CodeList>>` to allow for additional values.
- The role name `isComponent` was renamed to `component`.

PDF with UML diagram: [2019_11_08_Dynamizer with code lists.pdf](https://github.com/opengeospatial/CityGML-3.0CM/files/3825369/2019_11_08_Dynamizer.with.code.lists.pdf)

**Comment by thomashkolbe** [comment]
Please find attached the updated slides illustrating the usage of the finalised Dynamizer module: 
[2019_11_10_Dynamizer_Examples.pdf](https://github.com/opengeospatial/CityGML-3.0CM/files/3828792/2019_11_10_Dynamizer_Examples.pdf)

Here are three CityGML 3.0 test datasets. Each dataset contains the same building, but with different kinds of Dynamizers (two are making connections to an external sensor service using the OGC SensorThings API, one includes inline timeseries data): [Dynamizer_Examples.zip](https://github.com/opengeospatial/CityGML-3.0CM/files/3828800/Dynamizer_Examples.zip)

The three files validate against the most recent CityGML 3.0 GML application schema (branch: editor-model-updates): https://github.com/opengeospatial/CityGML-3.0Encodings/tree/editor-model-updates/CityGML/Schema
