### ISSUE TITLE
TINRelief issue

### ISSUE THREAD

**Issue by clausnagel** [opengeospatial/CityGML-3.0CM#97]
The current OCL constraint for `TINRelief` says that the `lodXMultiSurface` properties inherited from `core:AbstractThematicSurface` shall not contain a `GM_MultiSurface` as defined in the Core module, but only a `GM_TriangulatedSurface` (or subtypes thereof). But imho `lodXMultiSurface` cannot be restricted this way because `GM_MultiSurface` is not a supertype of `GM_TriangulatedSurface`. So I think the OCL constraint is invalid.

There are different ways to solve this:

1. The OCL constraint could be rewritten such that the `GM_MultiSurface` of each `lodXMultiSurface` property may only have exactly one `surfaceMember` of type `GM_TriangulatedSurface`. As a result, the triangulated surface representing the terrain would always have to be embraced by a multi-surface, which is not really nice in my opinion. And the encoding would be different compared to CityGML 2.0.
2. A new association is added from `TINRelief` to `GM_TriangulatedSurface`, and the use of the inherited `lodXMultiSurface` properties is prohibited by OCL constraints.

The second option would be consistent with how the geometry is currently defined for the other relief components like `BreaklineRelief` and `RasterRelief`. Another benefit would be that the representation of `TINRelief` remains identical to CityGML 2.0.

But I see another issue here: Although all relief components are derived from `core:AbstractThematicSurface`, they all prohibit the use of the inherited geometry properties and define their own additional ones (only `MassPointRelief` is a minor exception). So maybe `core:AbstractThematicSurface` is not the proper supertype?

That's why a third solution might be preferable:

We could introduce a new class `core:AbstractSpaceBoudary` in the core module, which takes the place of `core:AbstractThematicSurface` in the associations with `core:AbstractSpace`. The class `core:AbstractSpaceBoudary` should not define geometry properties. `core:AbstractThematicSurface` could then be defined as subtype of this new class. And also `AbstractReliefComponent` could be changed to be a subtype of `core:AbstractSpaceBoudary` and not of `core:AbstractThematicSurface` anymore.

Benefits:
* `AbstractReliefComponent` would not inherit useless geometry properties anymore that have to be prohibited by OCL constraints.
* The geometry of relief components can still be defined for the classes `TINRelief`, `MassPointRelief`, `BreaklineRelief` and `RasterRelief` as in the current Relief module.
* Thus, `TINRelief` would also remain identical to CityGML 2.0.

**Comment by TatjanaKutzner** [comment]
Based on the discussion in the web conference on 8 November 2019 the following things were updated in the latest commit:
- The class `AbstractSpaceBoundary` is introduced in the `Core` module as superclass of `AbstractThematicSurface`. The "bounds-boundary" association relates now `AbstractSpace` with `AbstractSpaceBoundary`.
- The classes `ReliefFeature` and `AbstractReliefComponent` in the `Relief` module are now defined as subclasses of `AbstractSpaceBoundary`.
- The class `TINRelief` is again associated with `GM_TriangulatedSurface` as in CityGML 2.0.
- The class `MassPointRelief` is again associated with `GM_MultiPoint` as in CityGML 2.0. In addition, it is associated with the class `AbstractPointCloud`.

PDF with UML diagram: [2019_11_08_Relief.pdf](https://github.com/opengeospatial/CityGML-3.0CM/files/3825363/2019_11_08_Relief.pdf)
